- src/expr.rs
- tests/test_expr.rs
This pull request adds the ability to parse `loop{}`.
A couple things: 
I had trouble with emacs and nom's syntax, so if the spacing is off, I apologize. Do you know how to make an editor handle spacing and indentation well for nom macros?
For the tests, I used tuples as statements in the body of the loop, because that's what I could get to parse.
Let me know comments and changes and I'll be glad to make them!
> Added an infinite loop parser and tests.

- src/attr.rs
- src/lit.rs
I had a bit of time earlier and wanted to dig into syn's code base. And why not implement a small thing at the same time? :)
Is this approximately what you meant in #42?
I haven't added any new tests for this (should I?), but used some of the impls in the code.
> Add a bunch of From impls for Lit

- src/lib.rs
- src/mac.rs
- tests/test_token_trees.rs
Token trees are much simpler than an AST. This makes them easier to work with when they are sufficient for the task at hand, such as for example [expanding a procedural macro](https://github.com/servo/html5ever/pull/217).
> Add parse_token_trees.

- .travis.yml
- Cargo.toml
- src/item.rs
- src/krate.rs
- src/lib.rs
- src/registry.rs
- tests/test_expand.rs
Example usage:
```rust
let mut registry = Registry::new();
registry.add_derive("Serialize", expand_serialize);
registry.add_derive("Deserialize", expand_deserialize);
registry.expand_file(src, dst).unwrap();
fn expand_serialize(input: MacroInput) -> Result<Expanded, String> { /* ... */ }
fn expand_deserialize(input: MacroInput) -> Result<Expanded, String> { /* ... */ }
```
> Expand custom derives

- src/lib.rs
Super simple one, just re-exporting `ExprKind` in the root. Or is there a specific reason this wasn't included?
> re-export ExprKind

- src/visit.rs
I'm not sure if it's the cleanest code I've ever written, but it seems to work well enough. 
Not sure what the best solution for `ConstExpr::Other` and `Ty::Mac` is, the current workaround I threw together for this patch isn't super nice.
> Add support for the 'full' feature to 'visit'

- Cargo.toml
This helps Servo avoid having two copies of it.
> Update unicode-xid dependency.

- Cargo.toml
- src/attr.rs
- src/ident.rs
- src/lib.rs
- src/lit.rs
- src/mac.rs
- syn_nom/Cargo.toml
- syn_nom/src/helper.rs
- syn_nom/src/lib.rs
- syn_nom/src/space.rs
I quickly threw this together, because this solution is super easy and straightforward.
Fixes #81.
> Expose the nom parsers in a public `parsing::` submodule

- Cargo.toml
- src/fold.rs
- src/lib.rs
Closes #43 .
Adds a new feature: "fold". 
The `Folder` trait allows implementing AST->AST transformations.
If the way it is implemented looks good, adding the documentation is trivial, but adding some tests will take some work.
> Implement Folder

- synom/src/helper.rs
- synom/src/lib.rs
This documents the rest of the parser macros, fixing #87.
I did it all in one go, and I didn't read over it, so there may be some mistakes. Please point them out when you look over it.
> Document the synom parser macros

- synom/src/helper.rs
The macro expansion of `separated_list` is broken as a '$' sign is missing.
The error is not visible from the CI builds. Probably because the macro is never expanded in the tests.
An example triggering the error is:
```rust
named!(comma_separated_types -> Vec<syn::Ty>,
separated_list!(punct!(","), syn::parse::ty)
);
```
> fix missing '$' before 'separgs' in expansion of separated_list

- src/lib.rs
- tests/test_macro_input.rs
I would like to have access to attribute parsing.
My use case is this: I am writing unit tests for `derive_builder`.
```rust
#[test]
fn setter_enabled() {
let attr = syn::Attribute{
style: syn::AttrStyle::Outer,
value: syn::MetaItem::Word(syn::Ident::new("foo")),
is_sugared_doc: false,
};
let field = BuilderField {
attrs: &vec![&attr],
/* ... */
};
assert_eq!(quote!(#field), quote!(
#[foo] pub foo: ::std::option::Option<String>,
));
}
```
would simplify to
```rust
#[test]
fn setter_enabled() {
let attr = syn::parse_outer_attr("#[foo]").unwrap();
let field = BuilderField {
attrs: &vec![&attr],
/* ... */
};
assert_eq!(quote!(#field), quote!(
#[foo] pub foo: ::std::option::Option<String>,
));
}
```
> public attribute parsers

- src/attr.rs
- src/ty.rs
- tests/test_generics.rs
- tests/test_macro_input.rs
- tests/test_meta_item.rs
Ref https://github.com/rust-lang/rust/pull/40346
This is a nightly-only feature (gated by `proc_macro` feature). Maybe you'd prefer it behind a feature instead of enabled by default?
> Support parsing attributes with arbitrary tokens.

- src/expr.rs
- src/fold.rs
- src/visit.rs
- tests/test_expr.rs
- tests/test_round_trip.rs
Fixes #109 
---
Before this change, `tests/rust/src/test/run-pass/catch-expr.rs` needed to be ignored because `syn` could not parse it, so it would fail the round-trip test. `syn` *can* parse it now with this change, but `syntex` still can't so the round-trip can't be tested anyway. So I've stopped ignoring the file, but also added its contents as a new test that validates the relevant parts of the parsed AST.
> Support parsing catch expressions.

- src/expr.rs
- src/fold.rs
- src/visit.rs
- tests/test_round_trip.rs
> Support parsing half-open ranges in patterns.

- README.md
- src/lib.rs
- tests/test_macro_input.rs
Also added #[deprecated] to parse_macro_input to pop warnings for those still using it (see #130).
> Added FromStr implementations to mirror the parse_* functions

- src/aster/ty.rs
- src/attr.rs
- src/constant.rs
- src/data.rs
- src/derive.rs
- src/expr.rs
- src/fold.rs
- src/generics.rs
- src/item.rs
- src/krate.rs
- src/lib.rs
- src/lit.rs
- src/mac.rs
- src/macros.rs
- src/op.rs
- src/ty.rs
- src/visit.rs
- synom/src/helper.rs
- tests/test_expr.rs
- tests/test_generics.rs
- tests/test_macro_input.rs
- tests/test_meta_item.rs
This commit is a relatively large rewrite of the AST that `syn` exposes. The
main change is to expose enums-of-structs rather than
enums-with-huge-tuple-variants. The best example of this is `ItemKind::Fn` which
changed from:
enum ItemKind {
Fn(Box<FnDecl>, Unsafety, Constness, Option<Abi>, Generics, Box<Block>),
...
}
to
enum ItemKind {
Fn(ItemFn),
...
}
struct ItemFn {
decl: Box<FnDecl>,
unsafety: Unsafety,
constness: Constness,
abi: Option<Abi>,
generics: Generics,
block: Box<Block>,
}
This change serves a few purposes:
* It's now much easier to add fields to each variant of the ast, ast struct
fields tend to be "by default ignored" in most contexts.
* It's much easier to document what each field is, as each field can have
dedicated documentation.
* There's now canonicalized names for …
> Rewrite the AST to be a bit more user-friendly

- .travis.yml
- Cargo.toml
- src/attr.rs
- src/data.rs
- src/expr.rs
- src/generics.rs
- src/item.rs
- src/lit.rs
- src/mac.rs
- src/macros.rs
- src/op.rs
- src/ty.rs
- synom/Cargo.toml
- tests/test_generics.rs
- tests/test_macro_input.rs
- tests/test_meta_item.rs
- tests/test_token_trees.rs
This commit moves all #[derive] annotations behind Cargo feature gates to add
the ability to strip them all out entirely. The `Clone` and `Copy` impls
continue to be enabled by default as they tend to be mega useful but other
equality/hash/debug impls are all default behind the `extra-impls` gate.
This commit, on my computer, has the following timings:
| features                      | before  | after
|-------------------------------|---------|------
| default                       | 3.67    | 2.96
| *none*                        | 1.78    | 0.49
| {printing, parsing}           | 3.71    | 2.57
| default + {full}              | 8.50    | 6.31
| {full}                        | 3.53    | 0.70
| {full, printing, parsing}     | 8.10    | 5.29
Closes #143
> Move all #[derive] impls behind Cargo feature gates

- src/krate.rs
In the `do_parse!(input, ...)` way of invoking nom-style macros, the "input" argument seems like a nom implementation detail that users aren't supposed to need to write.
> Use nom macro to declare parse method inside Synom trait

- src/attr.rs
- src/constant.rs
- src/data.rs
- src/derive.rs
- src/expr.rs
- src/generics.rs
- src/ident.rs
- src/item.rs
- src/krate.rs
- src/lit.rs
- src/mac.rs
- src/op.rs
- src/ty.rs
- synom/src/delimited.rs
- synom/src/helper.rs
- synom/src/lib.rs
- synom/src/tokens.rs
- tests/test_meta_item.rs
Fixes #150, #151 
The bulk of this patch is actually #150, as I needed to rewrite every `parse` signature to use the new types, and it was easy enough to just convert them into invocations of `named!` every time.
I also introduced a `Cursor` type alias in `synom` which I use instead of `&[TokenTree]` as the parser input type. I intend in #148 to change the `Cursor` type to be something other than `&[TokenTree]` so this will make my life easier in the future.
I use the type alias of `PResult<'a, O>` to refer to parser results (of the form written above).
> Switch from `IResult<I, O>` to `Result<(I, O), E>`

- src/attr.rs
- src/generics.rs
- src/ident.rs
- src/lit.rs
- src/mac.rs
- synom/src/cursor.rs
- synom/src/delimited.rs
- synom/src/lib.rs
- synom/src/tokens.rs
- tests/test_meta_item.rs
The new input type for parsers in `syn` with this patch is the type `synom::Cursor`. This is an unsafely implemented type, which holds raw pointers into a formatted `SynomBuffer` object. This change allows for a few things:
1. We no longer need to allocate a `Vec` every time we want to enter a delimited section. The cursor just moves into the correct part of the backing buffer, and
2. This sets us up to fix #148 as we no longer erase `None`-delimited spans from our input, and can both ignore them when parsing most inputs, while still being able to use them for expression parsing.
The new `synom::cursor` module in the first patch adds some unsafe code in order to implement the more efficient cursor. It would probably be a good idea to double-check that I'm not violating any of my …
> Switch away from using `&[TokenStream]` as the input type

- tests/test_round_trip.rs
We support parsing these now due to
https://github.com/alexcrichton/proc-macro2/issues/6 and
https://github.com/alexcrichton/proc-macro2/pull/8.
This fixes #114
> Enable round-trip tests for 128-bit integers

- src/lib.rs
- tests/test_token_trees.rs
#125 was fixed by the TokenStream changes, and this adds a test to make sure that doesn't change.
> Add a test to ensure that we round-trip literals faithfully

- src/expr.rs
- src/fold.rs
- src/lib.rs
- src/ty.rs
- src/visit.rs
- synom/src/helper.rs
- synom/src/lib.rs
- synom/src/tokens.rs
- tests/test_grouping.rs
- tests/test_round_trip.rs
This should fix #163.
This changes a bunch of stuff, adding a few new debugging tools which I found useful for fixing the test failures while writing these patches, some changes to `Ty`'s parsing, a ton of `Expr` parsing changes etc.
I have not written good tests for the precedence parsing yet. I have an idea of how to do it well, comparing us against `syntex` on rustc's source, like `test_round_trip` does, but I'm going to use `fold` to implement it, so I'll have to fix #166 before I can do that. This doesn't regress any tests though (it actually fixes a few of them!), and we aren't shipping this version of `syn` yet, so I would like to land this patch, and add the tests in a follow-up :).
> Handle precedence when parsing expressions

- src/expr.rs
- src/fold.rs
- tests/common/mod.rs
- tests/common/parse.rs
- tests/common/respan.rs
- tests/test_precedence.rs
- tests/test_round_trip.rs
This adds a test which, like test_round_trip, tests that our parser correctly parses the precedence of each expression.
It has a few caveats, which are documented in the respective parsers, which mostly exist because trying to compare ASTs parsed by two completely different parsers is a little tricky sometimes.
I also factored out some of the code from test_round_trip into a separate shared module, so that both test_round_trip and test_precedence can use it.
Finally I found some bugs in syn while writing this test (unsurprisingly), so I fixed those as well.
> Test our expression parser correctly parses precedence

- src/lib.rs
- tests/test_derive_input.rs
Fixes #167.
@dtolnay How do you feel about removing this type alias?
> Remove the MacroInput type alias

- .gitignore
- .gitmodules
- tests/common/mod.rs
- tests/test_precedence.rs
- tests/test_round_trip.rs
This removes the `tests/rust` submodule and instead moves to lazily cloning it
during tests. This helps work around the fact that git dependencies on `syn`
will pull in all submodules, and rust takes forever to clone. In short, the
intention here is to make git dependencies on `syn` bearable to avoid Cargo
auto-cloning submodules.
> Remove `rust` as a submodule

- src/expr.rs
- src/fold.rs
- src/visit.rs
- synom/src/tokens.rs
This adds support for `yield` expressions as added in https://github.com/rust-lang/rust/pull/43076
> Support for `yield` expressions

- src/data.rs
- src/expr.rs
- src/generics.rs
- src/item.rs
- src/lib.rs
- src/mac.rs
- src/ty.rs
- synom/src/delimited.rs
This is my first pass at making our `ToTokens` implementations more lenient when it comes to generating tokens for invalid ASTs. I have some comments in the patch in the places which I both a) noticed as I read through all of our `ToTokens` implementations, and b) didn't fix.
This patch contains a few large if conditionals, and I'm really not sure how to nicely format those in the style used by syn, so I just... gave up? I tried running rustfmt for inspiration, but the style `syn` uses is so far from rustfmt's suggestions right now that it felt out of place. I'd love suggestions as to how to fix them to not be so ugly.
Fixes #177
> Make `ToTokens` more lenient when generating tokens for invalid ASTs

- src/fold.rs
- src/ty.rs
- src/visit.rs
The proc-macro2 crate currently has a bug where a bare `_` token is classified
as an identifier, but this doesn't happen with the upstream `proc_macro` crate!
In preparation for fixing proc-macro2 this commit removes `syn`'s reliance on
this behavior.
> Fix `_` as an identifier by accident

- README.md
0.12 isn't on crates.io yet so having 0.12 as an example in the README.md is a bit confusing for the new users.
> Change README.md Cargo.toml version to 0.11

- src/ident.rs
Added couple of examples to demonstrate the usual needs for the Ident API. Also tweaked the prose a bit to remove the reference to the `syn!` macro. Left the keyword exception in, but it's now in reference to the various `parse_*` functions.
Also added a comment to the `Ident::new` for those people who might skip the examples and are just looking for a way to construct an `Ident`.
> Add examples to Ident

- Cargo.toml
- examples/dump-ast.rs
- synom/src/delimited.rs
- synom/src/span.rs
- synom/src/tokens.rs
I wrote this originally to make it easier for me to quickly test stuff like #196, and I figured it might be useful to have in tree. It's just a really simple example program that reads a file, parses it, and debug prints out the result.
I also cleaned up the debug output a bit as it was a little noisy.
> Add a dump-ast example program for dumping the AST for a single file

- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/item.rs
- src/lib.rs
- syn_codegen/src/main.rs
- tests/test_expr.rs
Side note: this pattern is sort of nice:
```rust
let item: &Item = /* ... */;
match *item {
Item::Mod(ref item) => {
do_something_with(&item.ident, &item.content);
}
Item::Fn(ref item) => {
do_something_with(&item.abi, &item.block);
}
/* ... */
}
```
Basically pattern matching on an `item` and rebinding the same name `item` just takes your variable and imbues it with those additional fields that exist on the type of item that it happens to be.
> Flatten ItemKind into an Item enum

- src/expr.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/item.rs
- src/lib.rs
- src/mac.rs
- src/ty.rs
- syn_codegen/src/main.rs
This is part of a move to standardize on abbreviating only those types in the AST that are abbreviated in Rust source code, like `impl` or `fn`. The grammar of Rust source code never abbreviates `macro` to `mac`, so this commit reflects that.
Field names are being kept as `mac` because `macro` is a reserved word.
> Rename Mac -> Macro

- src/expr.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/item.rs
- src/lib.rs
- src/ty.rs
The FunctionRetTy naming was copied from libsyntax. The new name uses 2 fewer non-standard abbreviations (where standard means used in Rust source code, like `impl` or `mod`).
> Rename FunctionRetTy -> ReturnType

- src/attr.rs
- src/data.rs
- src/derive.rs
- src/expr.rs
- src/generics.rs
- src/ident.rs
- src/item.rs
- src/lib.rs
- src/mac.rs
- src/op.rs
- src/ty.rs
- syn_codegen/src/main.rs
- synom/src/helper.rs
- synom/src/lib.rs
- synom/src/tokens.rs
- tests/test_grouping.rs
I am not dead set on this, but I think it is an improvement. This commit introduces a type macro `Token!` and parser macros `punct!` and `keyword!` used as follows.
<pre>
ItemExternCrate {
pub attrs: Vec<Attribute>,
pub vis: Visibility,
pub extern_token: <b>Token![extern]</b>,
pub crate_token: <b>Token![crate]</b>,
pub ident: Ident,
pub rename: Option<(<b>Token![as]</b>, Ident)>,
pub semi_token: <b>Token![;]</b>,
}
impl_synom!(ItemExternCrate "extern crate item" do_parse!(
attrs: many0!(call!(Attribute::parse_outer)) >>
vis: syn!(Visibility) >>
extern_: <b>keyword!(extern)</b> >>
crate_: <b>keyword!(crate)</b> >>
ident: syn!(Ident) >>
rename: option!(tuple!(<b>keyword!(as)</b>, syn!(Ident))) >>
semi: <b>punct!(;)</b> >>
(ItemExternCrate {
attrs: attrs,
vis: vis,
extern_token: extern_, …
> Token macros

- src/data.rs
- src/expr.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- src/item.rs
- src/lib.rs
- src/ty.rs
- syn_codegen/src/main.rs
- synom/src/helper.rs
- synom/src/lib.rs
- tests/test_derive_input.rs
- tests/test_generics.rs
- tests/test_precedence.rs
Rust source code does not abbreviate type -> ty (the way it abbreviates impl and mod, for example). This commit updates the naming in syn to reflect that.
> Rename Ty -> Type

- src/gen/visit.rs
- syn_codegen/src/main.rs
Should fix #190.
We can't add a lifetime to VisitorMut, as the references can't be allowed to outlive the call (given that we're mutating the struct ^.^). This should make some uses of `Visitor` nicer to use.
> Add a Visitor lifetime

- src/expr.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- tests/test_precedence.rs
Fixes #202 
Not sure if this is the best approach - I could also just keep `unsafe { }` and `{ }` having the same AST node kind, and only change the parsers, but `unsafe { }` felt different enough to me that I figured it'd be OK to make it a separate ExprKind.
> Separate unsafe blocks into a ExprKind variant

- src/expr.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- src/lib.rs
- src/ty.rs
- syn_codegen/src/main.rs
- tests/test_derive_input.rs
- tests/test_precedence.rs
This is built on top of #260.
This fixes #259.
> Generic arg refactor

- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/ty.rs
> Support literals in const generics without a block

- synom/Cargo.toml
- synom/src/cursor.rs
- synom/src/lib.rs
I'm not sure if we want this to be in the tree, but I've written code which does something like this to debug why and where a parse is failing multiple times.
I intentionally don't expose this as a feature on syn, as I don't want --all-features on syn to pick it up ('cause we use that for tests), but this unfortunately makes it a bit hard to use this feature when testing. I usually edit synom's Cargo.toml when I want to turn it on.
> Add a feature to synom for verbose parsing logging

- src/derive.rs
- src/punctuated.rs
- tests/test_derive_input.rs
These methods were removed in syn 0.12. They seem like an odd removal,
since they're pretty widely used in the wild. This adds these methods
back. Though `Fields` is the closest structurally to `VariantData`, I've
opted to put it on `DataStruct` instead, as it's in the location most
people will look for it. `fields.fields()` also reads really poorly.
Fixes #316
> Bring back `VariantData::fields` and `VariantData::fields_mut`

- src/generics.rs
NOTE: This PR is not yet ready to be merged. This adds only two of the
six needed accessors, and has no tests. I wanted to make sure that
this was a feature that would be accepted before spending the time to
finish this.
Within Diesel we have a bunch of places that do things like
`generics.params.iter()`. It'd be very helpful for syn to provide these
iterators for us.
This PR as written only contains the iterator for `type_params` (holy
crap I hate that name can we please rename `TypeParam` to
`TypeParameter`). The other iterators will be mechanically
identical.
If you're good with this feature I will implement the remaining
iterators and add tests.
> Add helpful accessors to Generics

- src/attr.rs
- tests/test_meta_item.rs
So proc_macro2::Literal doesn't have any boolean related variant which
means that a boolean value is put in a TokenNode::Term and not a
TokenNode::Literal which in turn means that those values were ignored
and resulted in an impossibility to parse booleans in an attribute.
Fixes #346
> Make Attribute::interprete_meta understand booleans

- Cargo.toml
- src/buffer.rs
- src/lib.rs
- src/synom.rs
This feature is enabled by default for backwards compatibility, but
it can be disabled in order to break the runtime dependency on the
dynamic library libproc_macro in the rustc toolchain.
This PR assumes that there is a version 0.5.0 or higher of `quote` on crates.io that includes dtolnay/quote#62. That is not yet the case (see https://github.com/dtolnay/quote/pull/62#issuecomment-368087621)
> Add a feature for linking to proc_macro.

- src/buffer.rs
- src/lib.rs
- src/synom.rs
When making this PR I found at least three ways to document the fact that some methods have more feature requirements in addition to those on the type/trait itself:
- Mention every feature needed for all methods:
```rust
/// ... `"parsing"` ...
impl ... {
/// ... `"parsing"` ...
fn unaffected_method(...) { ... }
/// ... `"parsing"` and `"proc-macro"` ...
#[cfg(feature = "proc-macro")]
fn affected_method(...) { ... }
/// ... `"parsing"` ...
fn other_unaffected_method(...) { ... }
}
```
- Mention every feature only for methods with additional requirements, features for other methods are inferred from required features for type/trait:
```rust
/// ... `"parsing"` ...
impl ... {
fn unaffected_method(...) { ... }
/// ... `"parsing"` and `"proc-macro"` ...
#[cfg(feature = "proc-macro")]
fn …
```
> Document `proc-macro` feature

- src/punctuated.rs
Refactor the Punctuated type for additional safety (found a bug in Extend impl) and hopefully performance.
~~Still needs a bit of work. The Debug formatter is currently broken and only prints the internal Vec without the trailing T.~~
The Debug impl is now fixed, which was surprisingly easy.
I'd love a code review, and I wonder if I should rebase both commits into one.
> Refactor Punctuated<T, P>

- src/ident.rs
- src/token.rs
Fixes #410, closes #408.
Backstory:
- To begin with, nightly treats `_` as an Op. Syn parses `_` patterns as PatWild and prints them back to tokens as Op.
- Nightly switches to treating `_` as Term and refuses to accept `Op('_')`.
- Syn silently and retroactively on existing releases begins parsing `_` as PatIdent instead of PatWild, printing to tokens as Term. This is because the `alt!(...)` parser responsible for parsing syn::Pat attempts `punct!(_)` first which looks for an Op, then falls through to `syn!(Ident)` which looks for a Term. Code that uses `punct!(_)` breaks. However, code that parses a syn::Pat and prints it to tokens continues to work because nightly is happy with `Term("_")`.
- Syn is updated to have `punct!(_)` accept `Term("_")` in addition to `Op('_')` as a fix for …
> Underscore followup

- src/parsers.rs
- src/synom.rs
```rust
#[macro_use]
extern crate syn;
use syn::Ident;
use syn::synom::Synom;
struct Flag {
name: Ident,
}
// Parses the custom keyword `flag` followed by any name for a flag.
//
// Example: `flag Verbose`
impl Synom for Flag {
named!(parse -> Flag, do_parse!(
custom_keyword!(flag) >>
name: syn!(Ident) >>
(Flag { name })
));
}
```
Fixes #244.
> Add a custom_keyword parser

- Cargo.toml
`proc-macro` 0.4.1 no longer works after https://github.com/dtolnay/syn/commit/446f7d6da0592127e7a89f8621d879967c24448d.
> Require proc-macro2 ^0.4.2

- src/data.rs
- src/punctuated.rs
Iterating over the fields is very useful, but I currently have a need to mutate the fields. I could implement this behavior locally in my project, but I think others might find this useful.
> Add an iter_mut method to Fields

- src/buffer.rs
- src/lib.rs
- src/synom.rs
This causes the proc-macro feature to be ignored for wasm-targets where proc-macro is not available. Currently, if a crate is to be built on wasm that depends on `syn`, the proc-macro feature from an actual proc-macro leaks into the build-environment of `syn`, causing the build to fail.
This patch enables me to build (and run) my crate on wasm-targets.
I'd be nice if this could be bumped into a 0.14 release. This is a concerted effort with [proc-macro2](https://github.com/alexcrichton/proc-macro2/pull/111), `syn`, `quote` and [stdweb](https://github.com/koute/stdweb/issues/257); all of which need patching to compile on wasm.
> Ignore proc-macro feature on wasm-target

- src/export.rs
- src/keyword.rs
- src/lib.rs
- src/parse.rs
- src/token.rs
*This is just some additional design and polish atop @kureuil's work in #480. Copied from documentation:*
---
```rust
macro_rules! custom_keyword {
($ident:ident) => { ... };
}
```
Define a type that supports parsing and printing a given identifier as if it were a keyword.
As a convention, it is recommended that this macro be invoked within a module called `kw` and that the resulting parser be invoked with a `kw::` prefix.
```rust
mod kw {
syn::custom_keyword!(whatever);
}
```
The generated syntax tree node supports the following operations just like any built-in keyword token.
- [Peeking](https://docs.rs/syn-next/0.15.0-rc3/syn/parse/struct.ParseBuffer.html#method.peek) — `input.peek(kw::whatever)`
- [Parsing](https://docs.rs/syn-next/0.15.0-rc3/syn/parse/struct.ParseBuffer.html#method.pa …
> Custom keywords

- src/export.rs
Hi,
#469 fixed building on wasm32 target but a later commit added code which broke it again. This PR changes the `cfg` attribute to match what #469 does.
Before:
```
$ cargo build --target wasm32-unknown-unknown
Compiling syn v0.15.4 (file:///.../syn)
error[E0432]: unresolved import `proc_macro`
--> src/export.rs:16:9
|
16 | pub use proc_macro::TokenStream;
|         ^^^^^^^^^^ Maybe a missing `extern crate proc_macro;`?
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: Could not compile `syn`.
```
After:
```
$ cargo build --target wasm32-unknown-unknown
Compiling syn v0.15.4 (file:///.../syn)
Finished dev [unoptimized + debuginfo] target(s) in 1.90s
```
I've tried compiling with all the feature combinations that are in …
> Fix building on wasm32 target.

- .travis.yml
- tests/clone.sh
This is a faster download, smaller on disk, and saves time in the cache steps on Travis.
> Download test suite as tgz rather than git

- tests/test_precedence.rs
```console
error[E0432]: unresolved import `rustc_data_structures::small_vec`
--> tests/test_precedence.rs:218:32
|
218 |     use rustc_data_structures::small_vec::OneVector;
|                                ^^^^^^^^^ Could not find `small_vec` in `rustc_data_structures`
```
From this change in nightly: https://github.com/rust-lang/rust/pull/53824.
> OneVector type alias has been removed

- tests/common/eq.rs
```console
error[E0027]: pattern does not mention field `inline`                          
--> tests/common/eq.rs:140:57                                               
|                                                                          
140 |                 let $name { $($field,)* $($ignore: _,)* } = self;        
|                                                         ^ missing field `inline`
...                                                                            
295 | spanless_eq_struct!(Mod; inner items);                                   
| -------------------------------------- in this macro invocation          
error[E0027]: pattern does not mention field `inline`                          
--> tests/common/eq.rs:141:65 …
```
> Compiler now tracks whether module declarations are inline

- build.rs
- src/export.rs
- src/parse_quote.rs
Fixes https://github.com/dtolnay/syn/issues/505#issuecomment-425401600.
> Call the right quote from parse_quote on sufficiently new compilers

- src/attr.rs
- src/lib.rs
- src/parse_macro_input.rs
- src/parse_quote.rs
- tests/test_meta_item.rs
The various meta item types have been missing `Parse` implementations.
This makes parsing the argument to Rust's proc macros difficult.
This patch provides Parse implementation for:
* Meta
* MetaList
* MetaNameValue
* NestedMeta
A first step towards the goals stated in #359.
> Implement Parse for meta item types

- build.rs
- src/error.rs
- src/lib.rs
- src/thread.rs
> Make parse errors implement Send and Sync

- src/error.rs
This commit is intended to expose the ability to have multi-token errors
on stable Rust right now. This commit also, though, hopes that `syn` can
largely stick to "one `Span` is all you need" everywhere for the time
being. The implementation here uses two spans internally for a
start/end, but that's not exposed through the API at all yet.
Closes #537
> Add an `Error::new_spanned` constructor

- src/attr.rs
- src/error.rs
- src/expr.rs
- src/ext.rs
- src/group.rs
- src/keyword.rs
- src/lib.rs
- src/lit.rs
- src/lookahead.rs
- src/parse.rs
- src/parse_macro_input.rs
- src/path.rs
- src/token.rs
- tests/test_ident.rs
Previously accessible as `syn::parse::Error` and `syn::parse::Result`.
I haven't fully made up my mind about this, but these have turned into a fairly nice general-purpose proc macro error type beyond just parsing. For example a derive macro that accepts attributes may want to use `syn::Error` as the error type for reporting a nonsensical application of some attribute, which is not exactly a parsing issue.
```rust
#[derive(Serialize)]
#[serde(untagged)]
struct S;
```
```console
error: #[serde(untagged)] can only be used on enums
--> src/lib.rs:5:9
|
5 | #[serde(untagged)]
|         ^^^^^^^^
```
> Export syn::Error and syn::Result from crate root

- src/buffer.rs
- src/error.rs
- src/group.rs
```rust
input.parse::<Ident>()?;
```
Before:
```console
error: expected identifier
--> src/main.rs:3:4
|
3 | m!([a]);
|    ^^^
```
After:
```console
error: expected identifier
--> src/main.rs:3:4
|
3 | m!([a]);
|    ^
```
```rust
let content;
bracketed!(content in input);
content.parse::<Ident>()?;
content.parse::<Ident>()?;
```
Before:
```console
error: unexpected end of input, expected identifier
--> src/main.rs:3:4
|
3 | m!([a]);
|    ^^^
```
After:
```console
error: unexpected end of input, expected identifier
--> src/main.rs:3:6
|
3 | m!([a]);
|      ^
```
> Use Group::span_open and span_close in error spans

- tests/test_precedence.rs
- tests/test_round_trip.rs
Closes #572 using the simplest approach.
> Ignore .sh-requiring tests on Windows

- codegen/Cargo.toml
- codegen/src/json.rs
- codegen/src/main.rs
- codegen/src/types.rs
- syn.json
The JSON file can be used by third party libs to build tools that
consume `syn` types.
The JSON is generated to `syn.json`. [Link](https://github.com/carllerche/syn/blob/introspect-json/syn.json).
Follow up to #579.
> Generate JSON file of all syn types

- codegen/src/gen.rs
- codegen/src/parse.rs
- codegen/src/types.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- syn.json
The JSON file now specifies `Ident` as part of `proc_macro2` and `Ident` / `Span` are no longer included in definitions.
This alters the generated visit / visit_mut / fold files only by reordering some items. I assume this is OK. If not, I can dig in a bit more.
> Reclasify Ident and Span as being from proc_macro2

- src/item.rs
- tests/clone.sh
- tests/common/eq.rs
rust-lang/rust#57760 "Support defining C compatible variadic
functions" changes the `FnDecl` and `FnSig` member `variadic` to
`c_variadic` and adds the `TyKind` variant `CVarArgs`. Update
`syn` to handle these changes.
Depends On: rust-lang/rust#57760
> Sync with Rust post C-variadic PR

- src/ident.rs
- src/token.rs
The punctuation tokens are structured as:
```rust
pub struct $name {
pub spans: [Span; $len]
}
```
It is good that this is consistent across punctuation with single and multiple spans. Accessing spans as `shl.spans[0]`, `shl.spans[1]` is fine for something like `Token![<<]`. But for tokens with a single span like `Token![;]` it would be nice to allow referring to `semi.span` as an alternative to `semi.spans[0]`.
This commit adds Deref and DerefMut impls to make that work:
```rust
use proc_macro2::Span;
use syn::Token;
fn main() {
let mut semi = Token![;](Span::call_site());
println!("{:?}", semi.spans[0]);
// New:
semi.span = Span::call_site();
println!("{:?}", semi.span);
}
```
I suspect many people (because that includes me) write code like this already without paying attention. Now …
> Pretend to have `span` field on punctuation with single span

- src/expr.rs
- src/path.rs
Added `Parse` impls for:  `loop`, `while` and `for` loops, `if` expressions and literals.
> Parse impls for more expr types

- build.rs
- src/ext.rs
- src/lib.rs
- src/lookahead.rs
- src/parse.rs
- src/sealed.rs
```rust
use syn::ext::IdentExt;
impl Parse for MySyntaxTree {
fn parse(input: ParseStream) -> Result<Self> {
if input.peek(Ident::parse_any) {...}
unimplemented!()
}
}
```
Fixes #522.
> Function to peek any ident

- codegen/src/fold.rs
- codegen/src/full.rs
- codegen/src/gen.rs
- codegen/src/main.rs
- codegen/src/operand.rs
- codegen/src/visit.rs
- codegen/src/visit_mut.rs
- src/gen/fold.rs
Separating the three mostly independent codegen steps into separate modules gives code that is much easier to follow for only 8% increase in lines of code.
```console
$ git diff --stat origin/master..HEAD -- codegen
codegen/src/fold.rs      | 260 +++++++++++++++++++
codegen/src/full.rs      |  20 ++
codegen/src/gen.rs       | 775 ++-------------------------------------------------------
codegen/src/main.rs      |   9 +-
codegen/src/operand.rs   |  38 +++
codegen/src/visit.rs     | 234 +++++++++++++++++
codegen/src/visit_mut.rs | 233 +++++++++++++++++
7 files changed, 817 insertions(+), 752 deletions(-)
```
> Split fold / visit / visit_mut codegen

- src/gen/fold.rs
- src/item.rs
- syn.json
- tests/common/eq.rs
Found them with `rg --sort path -C1 asyncness`.
As for the tests – I've run `cargo test --release --all-features` with rustc
nightly on macOS 10.13, but only after ignoring the two `#[test]` sections in
tests/test_precedence.rs, because it was giving me a stack overflow.
> Fix order to be "const async unsafe" everywhere

- src/group.rs
This loosens the lifetimes in group functions and macros such that, for example, the following code is allowed.
```rust
fn in_parens<'de>(tokens: syn::ParseBuffer<'de>) -> syn::Result<syn::ParseBuffer<'de>> {
let content;
syn::parenthesized!(content in tokens);
Ok(content)
}
```
I ran into this problem when integrating serde with syn, which creates a lot of odd lifetimes.
> Loosen group lifetimes

- src/expr.rs
Fixes #650.
This requires Rust 1.26.0, released May 2018: https://blog.rust-lang.org/2018/05/10/Rust-1.26.html#inclusive-ranges-with-.= . If that's not acceptable, I can implement another solution.
> Emit `..=` instead of `...` for inclusive range syntax in patterns.

- codegen/src/fold.rs
- codegen/src/visit.rs
- codegen/src/visit_mut.rs
- src/attr.rs
- src/custom_keyword.rs
- src/custom_punctuation.rs
- src/data.rs
- src/derive.rs
- src/discouraged.rs
- src/error.rs
- src/expr.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- src/item.rs
- src/lib.rs
- src/lit.rs
- src/lookahead.rs
- src/parse.rs
- src/parse_macro_input.rs
- src/parse_quote.rs
- src/punctuated.rs
- src/spanned.rs
- src/token.rs
- src/ty.rs
Fixes #670.
Nightly rustdoc is required to render these links for now, but that should be fine. At least this way they all point to the right place!
Some rustdoc issues that would have made this better:
- https://github.com/rust-lang/rust/issues/62830
- https://github.com/rust-lang/rust/issues/62833
- https://github.com/rust-lang/rust/issues/62834
> Switch to intra rustdoc links

- build.rs
- src/lib.rs
- src/macros.rs
Make rustdoc generate the correct `[src]` links by perserving spans in our macros.
`__check` makes sure you don't write the wrong keywords.
> preserve spans in macros to generate better rustdoc [src] links

- codegen/src/debug.rs
- src/bigint.rs
- src/expr.rs
- src/ident.rs
- src/lib.rs
- src/lifetime.rs
- src/lit.rs
- tests/debug/gen.rs
- tests/test_derive_input.rs
- tests/test_grouping.rs
- tests/test_lit.rs
> Switch to base10_digits() as the main numeric literal accessor

- src/attr.rs
- src/parse.rs
Fixes #523.
For example:
```rust
let e = item.attrs[0].parse_args::<Expr>()?;
```
- When there is no arg provided:
```console
error: expected attribute arguments: #[m::my_attr(...)]
--> src/main.rs:2:5
|
2 |     #[m::my_attr]
|     ^^^^^^^^^^^^^
```
- When the arg is unexpectedly empty:
```console
error: unexpected end of input, expected expression
--> src/main.rs:2:18
|
2 |     #[m::my_attr()]
|                  ^
```
- When the arg is weird in some way:
```console
error: unexpected token in attribute arguments
--> src/main.rs:2:18
|
2 |     #[m::my_attr >>]
|                  ^^
```
> Method to parse Attribute with better spans

- src/path.rs
I'm trying to update failure-derive to proc-macro2 v1 (and various other newer deps) and this API is needed to easily implement support for the ["_0" "_1" syntax that failure-derive offers](https://github.com/rust-lang-nursery/failure/blob/master/book/src/derive-fail.md#tuple-structs).
> Add Path::get_ident for consumer libraries

- src/item.rs
The equivalent conversion method already exists from `DeriveInput` to `Item`, however there is no mechanism for converting in the other direction.
These conversion methods may be handy for logic which wants to parse arbitrary items, and hand off enums, structs, or unions to existing `DeriveInput`-based code.
> Add conversions from Item{Struct,Enum,Union} into DeriveInput

- src/data.rs
There are a few situations where I've been using `fields.iter().len()`. This works, but having inherent `len()` and `is_empty()` methods would make things feel more idiomatic.
> Add `len` and `is_empty` methods to `Fields`

- src/item.rs
- tests/test_receiver.rs
The current behaviour of receiver parsing in syn is a bit complex, but I don't see a way to simplify it without making some breaking changes. I think we'd want the receiver would be a separate member of `Signature`, like `variadic`, and would support both the shorthand and typed forms. The remaining arguments would then be stored in `Signature` directly as a `Punctuated<PatType, Token![,]>`.
> Add a receiver getter to Signature, and clarify parsing behaviour

- src/data.rs
- src/discouraged.rs
- src/parse.rs
- src/token.rs
- tests/test_visibility.rs
As suggested in https://github.com/dtolnay/syn/pull/722#issuecomment-558451027, the Visibility patch (patch 2) does not introduce new APIs for observing 'unexpected' errors, and instead manually checks for 'content.is_empty()' when speculatively parsing in `Visibility`.
The final patch fixes 'unexpected' error propagation when using 'advance_to'. This ended up being more complex than I expected, as the fork's root parser is likely to set `unexpected` when it is dropped, which should not cause an error in the advanced stream. This was worked around using `Cell` directly within `ParseBuffer`, in addition to within `Rc`s. 
Fixes #720, #721
> Fix Visibility parsing errors, and optimize with 'advance_to'

- src/expr.rs
- src/item.rs
- src/stmt.rs
Resolves `// TODO: optimize using advance_to` comments throughout the codebase.
Fixes #654
> Optimize various parsers to avoid re-parsing

- Cargo.toml
- src/parse.rs
- src/token.rs
Before:
```console
impl Foo { fn b(a: i32, String) {} }
^ expected `:`
```
After:
```console
impl Foo { fn b(a: i32, String) {} }
^ expected `:`
```
Fixes #739.
> Point to closing delimiter when parsing punct past end of group

- src/expr.rs
- src/pat.rs
- tests/repo/mod.rs
https://github.com/rust-lang/rust/issues/67264
> Implement half-open range patterns

- src/expr.rs
- tests/test_stmt.rs
Fixes #773. The parsing of `&raw` as a raw reference operator should only kick in if `raw` is followed by `const` or `mut`.
> Fix raw operator parsing to require const keyword

- src/expr.rs
The most variants are not available unless syn is build with "full", which sometimes leads to [confusing situations](https://github.com/TeXitoi/structopt/issues/354)
> Explicitly mention Expr::* variants require "full"

- src/parse.rs
- tests/test_parse_buffer.rs
> Permit trailing empty Delimiter::None groups at the end of parse stream

- src/item.rs
- tests/repo/mod.rs
As tested by https://github.com/rust-lang/rust/blob/1836e3b42a5b2f37fd79104eedbe8f48a5afdee6/src/test/ui/parser/foreign-ty-syntactic-pass.rs.
```rust
extern "C" {
type A: Ord;
type A<'a> where 'a: 'static;
type A<T: Ord> where T: 'static;
type A = u8;
type A<'a: 'static, T: Ord + 'static>: Eq + PartialEq where T: 'static + Copy = Vec<u8>;
}
```
Closes #763. Required for https://github.com/dtolnay/cxx/issues/99.
> Parse ForeignItem `type` with generics and bounds

- src/pat.rs
This bit me a little: something like `None` or `MY_CONST` parse as a `PatIdent` but doesn't bind a variable as claimed.
> Add a caveat to PatIdent's description

- tests/common/mod.rs
- tests/test_precedence.rs
- tests/test_round_trip.rs
This prevents stack overflows in the test suite when run in debug mode on some platforms on some of the deeply nested rustc test cases.
6 MB is enough on my machine but I included a safety margin.
In release mode we need much less stack space; 1.5 MB is enough, which is below the default size.
> Raise rayon thread pool stack size

- Cargo.toml
- src/lit.rs
- tests/test_lit.rs
e.g. `br#"..."#suffix`, `b'?'suffix`, `'?'suffix`
Rust lexical grammar is nuts but this matches the behavior of libproc_macro.
> Parse suffix on byte string, byte, and char literals

- src/lit.rs
Dispatches to the individual accessors from #799.
> Add Lit::suffix accessor to get suffix of any lit

- src/item.rs
- tests/test_const_underscore.rs
(test is based on [rust/src/test/ui/parser/assoc-const-underscore-syntactic-pass.rs](https://github.com/rust-lang/rust/blob/8aa9d2014f4e5258f83b907e8431c59a33acdae7/src/test/ui/parser/assoc-const-underscore-syntactic-pass.rs))
Closes #760
> Parse const underscore in traits and impls

- src/item.rs
- tests/test_trait_inner_attr.rs
(test is based on [rust/src/test/pretty/trait-inner-attr.rs](https://github.com/rust-lang/rust/blob/8aa9d2014f4e5258f83b907e8431c59a33acdae7/src/test/pretty/trait-inner-attr.rs))
Closes #759
> Parse inner attributes in traits

- src/expr.rs
Currently, `parse::<Expr>()` parses outer attributes, but `parse::<Expr*>()` (e.g., `parse::<ExprMatch>()`)  does not parse outer attributes. It would be preferable if these behaviors are consistent.
> Parse outer attributes on Expr* structs

- src/item.rs
- tests/repo/mod.rs
It cannot be parsed as `Item{Const, Struct}` because `eq_token` and `expr` fields are not `Option`, so it parsed as `Item::Verbatim` [like `&raw [const|mut]` syntax](https://github.com/dtolnay/syn/blob/011b9dfc2d04bb1f2aee1b43e2bd88a9a067a568/src/expr.rs#L1495-L1497).
Closes #764
> Parse top level const/static without value

- src/item.rs
- tests/repo/mod.rs
It cannot be parsed as `ForeignItemStatic` , so it parsed as `ForeignItem::Verbatim` like `&raw [const|mut]` syntax.
Closes #762
> Parse extern static with value

- src/item.rs
- tests/repo/mod.rs
This covers [test/ui/parser/fn-body-optional-syntactic-pass.rs](https://github.com/rust-lang/rust/blob/8aa9d2014f4e5258f83b907e8431c59a33acdae7/src/test/ui/parser/fn-body-optional-syntactic-pass.rs) (by the first and second commits) and [test/ui/parser/fn-header-syntactic-pass.rs](https://github.com/rust-lang/rust/blob/8aa9d2014f4e5258f83b907e8431c59a33acdae7/src/test/ui/parser/fn-header-syntactic-pass.rs) (by the third commit).
Closes #761
> Parse syntactically accepted functions

- src/lib.rs
- src/ty.rs
- tests/repo/mod.rs
It cannot be parsed as `TypeBareFn`, so it parsed as `Type::Verbatim`.
Closes #765
> Parse mut self receiver in function pointer type

- src/item.rs
- tests/repo/mod.rs
It cannot be parsed as `ItemImpl`, so it parsed as `Item::Verbatim`.
Closes #766
> Parse const trait impls

- src/expr.rs
- src/pat.rs
Previously we would only report errors inside of a struct expression or struct pattern's braces after subsequent tokens parsed successfully, otherwise preferring any error in the subsequent tokens.
Before:
```console
error: expected expression
--> dev/main.rs:5:30
|
5 | let _ = Struct { a: b, c; }; ,
|                              ^
```
After:
```console
error: expected `,`
--> dev/main.rs:5:25
|
5 | let _ = Struct { a: b, c; }; ,
|                         ^
```
Closes #817.
> Error earlier on unexpected token in struct expr

- src/expr.rs
I must admit I have not extensively tested this, but the code is simple enough and taken from the support for const generics on types so I have a lot of confidence in this.
> Parse const generics on methods with feature(full)

- src/discouraged.rs
- src/expr.rs
- src/item.rs
- src/pat.rs
- src/path.rs
- src/stmt.rs
- src/ty.rs
This unstable feature was removed from rustc in https://github.com/rust-lang/rust/pull/57572.
> Remove parsing of extern:: paths

- src/expr.rs
- tests/test_expr.rs
This would happen in the expression `$macro!()` where $macro:ident.
Fixes https://crater-reports.s3.amazonaws.com/pr-72622/master%237726070fa755f660b5da3f82f46e07d9c6866f69/reg/fourier-0.1.0/log.txt.
> Parse macro call expr with None-delimited path

- src/ty.rs
- tests/test_ty.rs
This would happen in the type `$ty<T>` or `$ty<'a>` where $ty:ty.
Fixes https://crater-reports.s3.amazonaws.com/pr-72622/master%237726070fa755f660b5da3f82f46e07d9c6866f69/reg/gc-sequence-0.2.0/log.txt.
> Parse Type::Path containing None-delimited group segment

- src/expr.rs
- tests/test_expr.rs
This would happen in the expression `$struct {...}` where $struct:ident.
> Parse Expr::Struct containing None-delimited ident name

- src/buffer.rs
- tests/test_lit.rs
When rust-lang/rust#72388 re-lands, we may accumulate several 'layers'
of `None`-delimited groups. This commit ensures that we 'unwrap' all of
the layers, allowing consumers to avoid needing to handle these cases.
> Handle multiple nested `None`-delimited groups

- README.md
- dev/parse.rs
- examples/heapsize/heapsize_derive/src/lib.rs
- examples/lazy-static/lazy-static/src/lib.rs
- examples/trace-var/trace-var/src/lib.rs
- src/attr.rs
- src/error.rs
- src/lib.rs
- src/parse.rs
- src/parse_macro_input.rs
This is no longer required inside of proc-macro crates as of Rust 1.42.
https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#use-proc_macrotokenstream-now-works
> Remove extern crate proc_macro from docs

- src/lib.rs
- src/whitespace.rs
- tests/test_shebang.rs
As of https://github.com/rust-lang/rust/pull/71487 and https://github.com/rust-lang/rust/pull/73596, a file starting with `#!` is not necessarily a shebang if whitespace/comments after the `#!` are followed by `[`, making it an attribute.
```rust
#!//am/i/a/comment
fn main() {} // ^ shebang
```
```rust
#!//am/i/a/comment
[allow(dead_code)] // ^ not a shebang
fn main() {}
```
> Match rustc's new shebang handling 

- src/expr.rs
- tests/test_expr.rs
Previously `tuple.0. 0` would fail with:
```console
error: unexpected end of input, expected literal
--> dev/main.rs:5:19
|
5 |     let _ = tuple.0. 0;
|                   ^^
```
because we had done `split('.')` on the `0.` float literal token expecting to parse an integer index from both sides.
> Fix parse of `tuple.0. 0`

- src/item.rs
This lets `ItemImpl`s, i.e. `impl Trait for Type {}`, include parenthesized path arguments on `Trait`. An example would be `impl FnOnce() for X {}`.
This is in line with `rustc` which parses successfully, but bails later with "associated type bindings are not allowed here".
> Accept traits with parenthesized path arguments in impls

- src/parse_macro_input.rs
This would have been useful in https://github.com/dtolnay/cxx/pull/298
> Add case to parse_macro_input! to use a Parser function

- src/lit.rs
- tests/test_lit.rs
Previously, we'd parse `1e0` as a float but `1e_0` as an integer `1` with suffix `e_0`. This PR fixes it to parse as float, matching the behavior of libproc_macro.
> Parse as float even with `e` and numeric exponent separated by `_`

- src/error.rs
This trait method has been soft deprecated in libstd since 1.27.0 and hard deprecated since 1.42.0. Nothing should be using it and it's not able to return a meaningful message anyway. If anything, our message is less useful than the trait's default impl's message.
> Remove deprecated description method from Error impl

- src/lit.rs
```console
$ cargo check
warning: panic message contains braces
--> src/lit.rs:1283:30
|
1283 |             panic!("expected {{ after \\u");
|                              ^^
|
= note: `#[warn(panic_fmt)]` on by default
= note: this message is not used as a format string, but will be in a future Rust edition
help: add a "{}" format string to use the message literally
|
1283 |             panic!("{}", "expected {{ after \\u");
|                    ^^^^^
```
FYI: the current one is printed as `expected {{ after \u`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=45ed815fdfa7a54d42bdaa70a4659674
> Fix panic_fmt warning

- Cargo.toml
- src/attr.rs
- src/data.rs
- src/derive.rs
- src/expr.rs
- src/file.rs
- src/generics.rs
- src/group.rs
- src/item.rs
- src/lib.rs
- src/lit.rs
- src/mac.rs
- src/op.rs
- src/parse_macro_input.rs
- src/parse_quote.rs
- src/pat.rs
- src/path.rs
- src/punctuated.rs
- src/stmt.rs
- src/ty.rs
Closes #731 now that https://github.com/rust-lang/rust/issues/43781#issuecomment-568829501 have both been fixed in rustdoc.
> Set doc(cfg(...)) on feature gated APIs

- src/expr.rs
- src/stmt.rs
- tests/repo/mod.rs
- tests/test_precedence.rs
Part of #921. Const blocks in pattern position to be implemented separately.
> Parse const blocks in expression position

- src/pat.rs
- tests/repo/mod.rs
Part of #921. The remaining work on const blocks is use in range patterns, since those follow a different parse. In pat outside of ranges, const block will parse to `Pat::Verbatim`. In ranges, the range bounds are represented as Expr in the syntax tree so we'd need to parse to `Pat::Range` containing the const block range bounds as `Expr::Verbatim`.
> Parse const blocks in pattern position

- src/item.rs
- tests/test_item.rs
Fixes #941.
This was broken by #936.
> Fix impl parsing with None-delimited grouped path

- src/file.rs
The example listed in the documentation for `syn::File` had output that seems to be for a previous version of the code in the example - this just updates that.
> update `File` example program output

- src/ty.rs
- tests/test_ty.rs
Previously, `peek2` was used to check for `::` or `<` following a
`None`-delimited group. However, `peek2` will look *inside* a
`None`-delimited group, so this code would treat input like
`{{ Vec<u8> }}` as having an angle bracket *after* the `None`-delimited
group.
We now consume the `None`-delimited group by parsing it, and then use
`peek` to check for tokens that occur *after* the `None`-delimited
group.
> Fix parsing of path type wrapped in a `None`-delimited group

- src/path.rs
This allows e.g. the following DeriveInput to parse even without the `"full"` feature enabled. This is going to make increasingly common appearance with the stabilization of min_const generics in Rust 1.51 (https://github.com/rust-lang/rust/pull/79135).
```rust
pub struct S {
array: Array<10>,
}
```
> Parse simple literal const generic path args even without "full"

- src/item.rs
- tests/test_item.rs
Rustc parses all of the following. [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=00b4ab96698af6d42f37be4f27c2aaba)
```rust
trait Trait where {}
trait Trait: where {}
trait Trait: Sized where {}
trait Trait: Sized + where {}
```
Syn was failing to parse if there wasn't at least one supertrait after the `:`.
> Parse empty supertrait list

- src/ty.rs
The original implementation was going through Punctuated's impl IntoIterator\<Item = T\> followed by Extend\<T\>, which throws away the old punctuation tokens P and creates brand new Default ones, losing the spans.
Fixes #959.
> Fix loss of punctuation spans on TypeTuple parse

- src/punctuated.rs
Debugging proc macros is very difficult as we can't easily get
backtraces into the proc macro code. Improved error messages will
hopefully give some hint to the user on what the problem is.
> Replace assertions in Puctuated with more helpful panic messages

- src/lifetime.rs
This matches the `span` and `set_span` accessors we provide on all the various `Lit` variant types.
Lifetimes are ordinarily treated as a single token. Only the proc macro API splits them into `'` punctuation and ident. Consequently the span of those two things is normally identical, except in pathological case when manually constructed from within a proc macro with differing spans. Thus, requiring macros to decide whether to write `lifetime.apostrophe.span` or `lifetime.ident.span()` for that span makes the code misleading. The new accessors reflect the fact that really there is only one span involved.
For example rustc parsers `'a` as the following TokenStream, in which byte range `95..97` covers both characters of the entire `'a` token.
```console
TokenStream [
Punct {
ch: '\'', …
```
> Add Lifetime span getter and setter

- src/item.rs
- tests/test_item.rs
> Permit empty trait bounds after colon on type item

- tests/repo/mod.rs
Open issues:
- generic associated type equality constraints &mdash; #979
- const generic parameter default values &mdash; #980
- pub macro_rules &mdash; #981
- leading vert in or-patterns &mdash; #982
- static with omitted type &mdash; #983
- placeholder type in type parameter position &mdash; #984
> Update test suite to nightly-2021-03-26

- src/pat.rs
- tests/repo/mod.rs
- tests/test_pat.rs
Closes #982. This matches the upstream rustc parser change in https://github.com/rust-lang/rust/pull/81869.
> Parse leading vert in nested patterns

- .github/workflows/ci.yml
This cuts about 18 seconds from our longest running job, by not building doc tests in the same job as the main test suite.
> Move documentation testing to doc CI job

- src/expr.rs
ExprArray can be parsed directly rather than going through impl_by_parsing_expr. This makes the following type of thing possible:
```rust
let x: ExprArray = input.parse()?;
let _: Token![+] = input.parse()?;
let y: ExprArray = input.parse()?;
```
which previously would have failed due to the `+` being eagerly consumed as part of `x`, making it into ExprBinary, and thereby failing to parse `x` as ExprArray.
> impl Parse for ExprArray

- src/path.rs
- tests/repo/mod.rs
> Parse generic associated type equality constraint

- src/expr.rs
> Report no precedence for `:` binary operator in non-full mode

- Cargo.toml
- src/error.rs
Lex error spans were added to proc-macro2 in https://github.com/alexcrichton/proc-macro2/pull/283.
> Preserve span of LexError on conversion to syn::Error

- src/attr.rs
- src/expr.rs
- src/item.rs
Appending inner attrs onto an existing attributes vector, instead of into a separate vector which the caller is responsible for combining together, is more amenable for an upcoming refactor -- it's more convenient to pass `&mut attrs` as an argument to various helpers, rather than trying to pass back inner attrs as a tuple element in return position, which is always clumsy.
```rust
// easy
let thing = parse_thing(input, x, y, attrs)?;
// clumsy
let (thing, inner_attrs) = parse_thing(input, x, y)?;
attrs.extend(inner_attrs);
```
The rustc parser follows the same strategy, such as in https://github.com/rust-lang/rust/blob/b849326744a8eec939e592f0ab13bff85cc865d3/compiler/rustc_parse/src/parser/item.rs#L33-L48.
> Refactor inner attribute parsing

- src/data.rs
- src/derive.rs
- src/item.rs
Corresponding to the rustc change in https://github.com/rust-lang/rust/pull/84414.
> Parse inner attrs on structs, enums, unions, variants

- src/item.rs
Example of panicking impl:
```rust
fn main() {
let _ = syn::parse_str::<syn::ItemImpl>("impl () for () {}");
}
```
> Fix possible panic on invalid ItemImpl

- src/item.rs
- tests/test_item.rs
Rustc's parser allows them.
```rust
#[cfg(any())]
pub impl _ {}
#[cfg(any())]
crate impl crate for crate {}
```
> Parse visibility on impl blocks

- src/item.rs
- tests/test_item.rs
rustc syntactically accepts this.
```rust
#[cfg(any())]
impl<T = ()> () {}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5f585898bde387b258cecc57558e9aa9)
> Parse type parameter defaults on impl blocks

- src/ty.rs
- tests/test_ty.rs
This is not valid syntax in Rust.
```console
error: expected identifier, found keyword `dyn`
--> src/main.rs:1:18
|
1 | type T = for<'a> dyn Trait;
|                  ^^^ expected identifier, found keyword
error: expected one of `(`, `+`, `::`, `;`, or `<`, found `Trait`
--> src/main.rs:1:22
|
1 | type T = for<'a> dyn Trait;
|                      ^^^^^ expected one of `(`, `+`, `::`, `;`, or `<`
```
Fixes #1041.
> Reject for<'a> dyn Trait

- src/lib.rs
The free-standing `parse2`'s documentation doesn't mention that it can error even if the underlying `Parse::parse` succeeds.  
[This tripped me up a bit.](https://github.com/Tamschi/call2-for-syn/issues/1)
This pull request copies the relevant phrase from `Parser::parse2`'s documentation.
> Document completion check on syn::parse2

- tests/repo/mod.rs
- tests/test_precedence.rs
Previously this would break test_precedence on something like `f::<-1>()` by parenthesizing to `f::<-(1)>()`, which is invalid syntax.
> Don't break negative literal const generic args with parenthesization

- src/stmt.rs
- tests/repo/mod.rs
- tests/test_precedence.rs
> Parse let-else syntax

- src/item.rs
- src/stmt.rs
The provisional syntax was deleted from nightly in https://github.com/rust-lang/rust/pull/63180.
> Delete old 'existential type' provisional syntax

- .gitattributes
This will render the files collapsed by default in diffs.
<br>
> Set src/gen to be considered generated by linguist

- tests/repo/mod.rs
Notably https://github.com/rust-lang/rust/pull/84571 has been reverted upstream in https://github.com/rust-lang/rust/pull/88775, and https://github.com/rust-lang/rust/pull/88690 needs to be implemented in syn which I've filed https://github.com/dtolnay/syn/issues/1068 to track.
> Update test suite to nightly-2021-09-22

- src/export.rs
- src/parse_quote.rs
The origin of this was 7d6a7b8979ae517ab4ec0dca3173c21c9f456ca8 which was written against quote 0.4, in which the return type of `quote!` was different from `TokenStream`. Now that `quote!` simply produces `TokenStream` there is no longer a need for a conversion there.
> Delete unneeded From conversion from parse_quote

- src/ty.rs
This closes an inconsistency between #1077 and #1074. The implementation from #1074 (`TypeImplTrait`) is the correct termination condition. For example the following would fail to parse prior to this PR:
```rust
fn main() {
let _: (dyn ToString + ,);
}
```
After this PR it parses successfully, matching `rustc` which accepts this program since 1.18.0.
> Invert TypeTraitObject exit condition to match TypeImplTrait

- src/ty.rs
- tests/test_ty.rs
> Fix bare non-dyn trait object trailing plus exit condition

- src/ty.rs
Matching the APIs already provided on `Type` and `TypeTraitObject`.
Impl trait containing `+` is not allowed in all syntactic positions. For example `fn f() -> impl Copy + 'static {}` is legal syntax but `fn f() -> &'static impl Copy + 'static {}` is not.
> Add a without_plus parser for TypeImplTrait

- src/ty.rs
This allows the `Type` parser to reject things like `&'static impl Copy + 'static`, which is not syntactically a legal type but was previously accepted.
> Propagate allow_plus from Type::parse to dyn and impl

- src/punctuated.rs
The `d` names stood for "delimiter" and are from prior to f2cfd72935d4bc7379c38c729062fc3ff2bd78de which renamed the type from `Delimited` to `Punctuated`.
> d->p variable naming in Punctuated implementation

- src/generics.rs
- src/path.rs
- src/ty.rs
- tests/test_path.rs
> Parse parenthesized path arguments with disambiguator

- src/stmt.rs
- tests/repo/mod.rs
Previously the stmt attributes on something like:
```rust
#[allow(unused)]
let Some(chaenomeles) = value else { return };
```
would just be lost during parsing.
> Preserve attributes on let-else stmt

- src/parse_quote.rs
The rustdoc bug was fixed by https://github.com/rust-lang/rust/pull/76934.
> Rely on rustdoc to resolve Punctuated<T, P> to an intra doc link

- tests/repo/mod.rs
#1125. This picks up the new tests from https://github.com/rust-lang/rust/pull/88642.
> Advance test suite past the let-chains PR

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- syn.json
- tests/debug/gen.rs
- tests/repo/mod.rs
Uncovered by the new tests from https://github.com/rust-lang/rustfmt/pull/5150.
> Fix static async closure keyword order

- src/pat.rs
- tests/test_stmt.rs
> Parse `..` pattern in pattern of let

- src/expr.rs
- tests/test_expr.rs
> Reject postfix operators after cast

- src/parse.rs
> Implement extra-traits for syn::parse::Nothing

- src/data.rs
- src/derive.rs
- src/expr.rs
- src/item.rs
This mirrors https://github.com/rust-lang/rust/pull/83312, which removed support for this syntax from rustc.
> Remove support for inner attributes on non-block expressions

- src/ty.rs
- tests/test_ty.rs
> Fix panic on comma after `mut self` in bare fn type

- build.rs
- codegen/src/clone.rs
- codegen/src/debug.rs
- codegen/src/fold.rs
- codegen/src/hash.rs
- codegen/src/visit.rs
- codegen/src/visit_mut.rs
- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/item.rs
- src/lib.rs
- src/macros.rs
- src/pat.rs
- src/ty.rs
This follows through on the comments on the `__TestExhaustive` variants promising that their purpose will be substituted with a `deny(reachable)` rustc lint once one is available.
https://github.com/dtolnay/syn/blob/ac68efab9576ab0f79633a48ebee5cca7321ddde/src/expr.rs#L247-L251
That lint is now landing as `non_exhaustive_omitted_patterns` in Rust 1.57. The correct way to use it for checking exhaustivity of a match is:
```rust
match expr {
Expr::Array(e) => {...}
Expr::Assign(e) => {...}
...
Expr::Yield(e) => {...}
#[cfg_attr(test, deny(non_exhaustive_omitted_patterns))]
_ => { /* some sane fallback */ }
}
```
> Switch non exhaustive syntax tree enums to use #[non_exhaustive]

- src/lookahead.rs
Given that a colleague also was not able to spot my mistake on its own I know three people which missed the this issue.
It might be obvious for those with a better understanding so please feel free to reject (or reword) this proposal :)
https://discord.com/channels/273534239310479360/512792629516173323/960864849305432095
> Improve lookahead documentation

- src/expr.rs
- src/pat.rs
Fixes a small issue where the `RangeLimits` enum didn't implement `ToTokens` when it probably should have.
> #1157 implement ToTokens for RangeLimits enum

- src/ty.rs
The old syntax is now a compile error, and it makes it difficult for users to search when they are looking for the keyword "dyn" on the documentation.
> Added `dyn` to Type::TraitObject docs

- .github/workflows/ci.yml
- src/buffer.rs
It looks like the only outstanding issue aliasing issue in this repo
(with raw pointer tagging) was this one move of a Box after saving a
pointer to the allocation that the Box guards. This is UB according to
the Stacked Borrows with raw pointer tagging in combination with the way
rustc applies noalias to Box. As is often the case, the resolution here
is to convert the Box down to a raw pointer before a pointer into the
allocation is created.
It is unclear to me if the spec will change and make this code valid without this PR. In https://github.com/rust-lang/unsafe-code-guidelines/issues/326 I've advocated for removing this special property from `Box` altogether. But by the same token, it's entirely possible that this code is UB today because it does aliased access through a `noalias` …
> Avoid Box invalidation to be compatible with tag-raw-pointers

- src/custom_keyword.rs
Fixes build when `Some` symbol is redefined in scope where `custom_keyword` macro is invoked.
> Use Some from $crate

- Cargo.toml
- examples/dump-syntax/Cargo.toml
- examples/heapsize/Cargo.toml
- examples/lazy-static/Cargo.toml
- examples/lazy-static/example/Cargo.toml
- examples/trace-var/Cargo.toml
- examples/trace-var/example/Cargo.toml
IIRC the reason it was not set up this way originally was that the examples used a newer edition than what was supported by the top-level crate. This made `cargo generate-lockfile` fail.
> Add all examples into top-level workspace

- benches/file.rs
The only way libproc_macro currently exposes to iterate a TokenStream is by value, i.e. there is no `impl IntoIterator for &TokenStream`. So a syn benchmark can't do anything without a clone and drop of the TokenStream on every iteration. This PR adds a benchmark that measures just the clone and drop, so that we can subtract and tell how long only the syn::parse2 is taking.
```console
test baseline   ... bench:     655,804 ns/iter (+/- 54,279)
test parse_file ... bench:   5,625,961 ns/iter (+/- 372,480)
```
> Add baseline benchmark to distinguish TokenStream::clone from syn::parse2

- benches/file.rs
This function accounts for a surprisingly high fraction of total parse time.
- 12%: `TokenStream::clone`
- 29%: `TokenBuffer::inner_new`
- 59%: everything else
I bet there are ways to bring that 29% down significantly.
```console
test baseline            ... bench:     650,636 ns/iter (+/- 15,705)
test create_token_buffer ... bench:   2,250,402 ns/iter (+/- 32,605)
test parse_file          ... bench:   5,477,355 ns/iter (+/- 114,418)
```
> Add a benchmark of TokenBuffer::inner_new

- src/buffer.rs
This looks like an easy 4% improvement for the new TokenBuffer::inner_new benchmark.
> Skip drop of entry known to be Entry::End placeholder

- src/path.rs
- tests/repo/mod.rs
Rustc appears to have settled on no ordering restriction beyond lifetimes going first.
> Preserve ordering of associated type constraints relative to types

- src/lib.rs
- src/parse_macro_input.rs
https://github.com/rust-lang/rust/issues/62830 has been fixed.
> Remove workaround for mod@crate::parse rustdoc links

- src/lit.rs
`crate::parse_str::<TokenStream>` is gonna turn &amp;str into TokenStream into TokenBuffer into TokenStream. Only the first conversion is needed in this context.
> Bypass a round trip through TokenBuffer in LitStr::parse

- src/buffer.rs
This looks like a small perf win:
```rust
flat-tokenbuffer
test baseline            ... bench:     751,638 ns/iter (+/- 37,662)   [0.714ms..0.789ms]
test create_token_buffer ... bench:   2,624,105 ns/iter (+/- 218,503)  [2.416ms..2.843ms]
test parse_file          ... bench:   6,546,490 ns/iter (+/- 285,880)  [6.261ms..6.832ms]
main
test baseline            ... bench:     766,913 ns/iter (+/- 35,923)   [0.731ms..0.802ms]
test create_token_buffer ... bench:   2,888,407 ns/iter (+/- 167,829)  [2.721ms..3.056ms]
test parse_file          ... bench:   6,737,680 ns/iter (+/- 492,060)  [6.316ms..7.160ms]
```
Replaces #1196. With a flat tokenbuffer, implementing `Ord` for `Cursor` will become trivial.
I did try a bit to make `Cursor` store `&[Entry]` directly, but I was having trouble doing so as …
> Use a flat layout for TokenBuffer

- benches/file.rs
- benches/rust.rs
Without this, it just hits the error message added in #798.
```console
$ cargo bench …
Compiling syn-test-suite v0.0.0
ERROR:  use --all-features
Syn's test suite normally only works with all-features enabled.
Run again with `--all-features`, or run with `--features test`
to bypass this check.
error: could not compile `syn-test-suite`
warning: build failed, waiting for other jobs to finish...
```
> Fix instruction for running benchmarks

- Cargo.toml
See https://github.com/dtolnay/proc-macro2/issues/353.
Without this, our benchmarks fail against the current contents of the rust-lang/rust repo.
```console
$ cargo test --release --bench rust --features full,test
871050 lines in 12914 files
read_from_disk:     elapsed=0.170s
tokenstream_parse:  FAIL tests/rust/src/test/ui/json/json-bom-plus-crlf-multifile-aux.rs
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `12913`,
right: `12914`', benches/rust.rs:122:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> Pull in proc-macro2 1.0.46 for byte order mark fix

- src/expr.rs
- src/ty.rs
> Fix left shift after macro metavariable in type position

- src/buffer.rs
- src/verbatim.rs
- tests/regression/issue1235.rs
New version of #1196 now that #1223 has changed token buffers to a flat layout, making the comparison trivial to implement.
As additional motivation and since it was first discovered in #1196, fixes #1235. The issue has nothing to do with `eq` comparing the scope pointer; in fact, the involved pointers actually have the same scope. Properly fixing the issue requires the ability to compare cursors in order to detect the case where the verbatim end is inside of a `None`-delimited group we previously would have stepped over.
I removed the check for scope equality here, as it is much more useful to be able to be able to compare cursors which don't necessarily have the same scope end (e.g. to determine which of multiple speculative parses got the furthest). Additionally, we actually now rely …
> Implement `PartialOrd` for `Cursor`

- src/buffer.rs
- src/lib.rs
- src/verbatim.rs
How does this look @CAD97? I was hesitant about directly exposing a pointer comparison across unrelated allocations.
```rust
use syn::buffer::TokenBuffer;
let a = TokenBuffer::new2("...".parse().unwrap());
let b = TokenBuffer::new2("...".parse().unwrap());
println!("{:?}", a.begin().partial_cmp(&b.begin()));
```
> Restrict PartialOrd comparison to only tokens in the same buffer

- src/path.rs
I've found this to be at least as often useful as `is_empty` is.
> Make PathArguments::is_none() public

- src/drops.rs
- src/lib.rs
- src/punctuated.rs
- tests/test_iterators.rs
> Infer may_dangle on type parameters of Punctuated iterator Drop impls

- src/generics.rs
The links to the reference do not fully compensate for the lack of examples yet they allow even less experienced rust developers understand which items are represented by [Generics](https://docs.rs/syn/latest/syn/struct.Generics.html) struct.
> Added a note on generics struct

- .github/workflows/ci.yml
- .github/workflows/pre_ci.yml
When a branch is used to open a PR in the branch's own repository, GitHub will trigger `on: push` workflows against the head commit of the PR, and `on: pull_request` workflows against a merge commit between the head commit
and the PR's base branch (typically master).
Often times those 2 sets of jobs end up running against identical trees. This is the case if there have been no commits on the base branch since when the PR's head branch was forked from the base branch.
This PR adds a workflow to detect this common scenario and provides a way to bypass CI from running redundantly on the merge commit.
> Prevent actions duplication on noop merge commits

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/fold.rs
- syn.json
Closes #678. That syntax no longer seems on track for stabilization.
> Delete field reserved for unstable &raw reference syntax

- src/pat.rs
Previously this buggy parser would permit all kinds of bogus syntax such as `Struct { 0 asdf }` and `Struct { box ref mut 0: asdf }`.
> Fix FieldPat parsing logic

- codegen/src/clone.rs
- codegen/src/debug.rs
- codegen/src/eq.rs
- codegen/src/file.rs
- codegen/src/fold.rs
- codegen/src/hash.rs
- codegen/src/json.rs
- codegen/src/main.rs
- codegen/src/parse.rs
- codegen/src/snapshot.rs
- codegen/src/version.rs
- codegen/src/visit.rs
- codegen/src/visit_mut.rs
- codegen/src/workspace_path.rs
Previously this would fail with _"Error: No such file or directory (os error 2)"_ if run as `cargo run --manifest-path codegen/Cargo.toml`.
> Make codegen runnable from any directory

- src/parse_macro_input.rs
Following #1267 this is no longer needed.
> Delete ParseMacroInput trait

- src/mac.rs
- src/token.rs
This code is going to be shared with an upcoming redesign of `Attribute`, since the attribute syntax also involves macro delimiters containing arbitrary tokens: `#[pa::th(...)]`, `#[pa::th[...]]`, `#[pa::th { ... }]`.
> Refactor printing of delimiter tokens

- src/attr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- src/lit.rs
- src/parse.rs
- src/path.rs
- syn.json
- tests/debug/gen.rs
- tests/test_attribute.rs
- tests/test_derive_input.rs
- tests/test_expr.rs
- tests/test_generics.rs
- tests/test_item.rs
- tests/test_meta.rs
- tests/test_precedence.rs
- tests/test_shebang.rs
The previous representation is from before the syntax permitted by the language for attributes was quite as pinned down as it's been since then.
> Update Attribute representation

- examples/trace-var/trace-var/src/lib.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- src/stmt.rs
- syn.json
- tests/debug/gen.rs
- tests/test_stmt.rs
Currently let-else statements are parsed as `ExprVerbatim` (i.e. they are not parsed internally).
*let-else* statements are in beta now, so they will most probably appear in stable in November. Therefore, I think, now is the right moment for adding full parsing implementation.
This PR adds such parsing implementation to syn.
Fixes: https://github.com/dtolnay/syn/issues/1159
> Support full let-else statement parsing

- src/stmt.rs
Fixes https://github.com/dtolnay/syn/pull/1231#discussion_r1051508698.
The following are not valid syntax in Rust.
```rust
let true = false else 'label: { return; };
```
```rust
let true = false else #[foo] { return; };
```
> Fix attrs and labels incorrectly accepted on let-else diverge block

- codegen/src/fold.rs
- codegen/src/visit.rs
- codegen/src/visit_mut.rs
- src/attr.rs
- src/buffer.rs
- src/data.rs
- src/derive.rs
- src/expr.rs
- src/ext.rs
- src/file.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- src/item.rs
- src/lib.rs
- src/mac.rs
- src/op.rs
- src/parse.rs
- src/pat.rs
- src/path.rs
- src/punctuated.rs
- src/spanned.rs
- src/stmt.rs
- src/ty.rs
This was originally deferred from #925.
> Delete all 'available only if' comments in favor of doc(cfg())

- src/pat.rs
All the other structs on https://docs.rs/syn/1.0.107/syn/index.html have a `.` at the end of their doc-comment, only `PatRest` is missing one.
> Add missing dot in documentation comment of `PatRest`

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- src/pat.rs
- syn.json
- tests/debug/gen.rs
- tests/test_precedence.rs
This seems sufficiently likely to land in stable Rust eventually.
Tracking issue: https://github.com/rust-lang/rust/issues/76001
> Add Expr::Const variant for const blocks

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- syn.json
- tests/debug/gen.rs
Tracking issue: https://github.com/rust-lang/rust/issues/85077
> Add Expr::Infer variant for inferred const generic arguments

- src/pat.rs
The previous parser was parsing negative paths and negative const blocks, which are not legal syntax in Rust.
```console
error: expected pattern, found keyword `self`
--> src/main.rs:78:10
|
78 |         -self::CONST => {}
|          ^^^^ expected pattern
error: expected pattern, found keyword `const`
--> src/main.rs:82:10
|
82 |         -const { 0i32 } => {}
|          ^^^^^ expected pattern
```
> Enforce that only literal patterns can be unary negated

- src/pat.rs
- tests/test_precedence.rs
Now that negative literals work reliably... #1305.
> Fold negative sign of unary pattern into the Lit

- src/error.rs
- src/thread.rs
Previously if you took a syn::Error with a non-call_site span, moved it to a different thread, cloned it, moved the clone back to the original thread, and called span() on that, you'd have lost the original span.
Now the span will be preserved during clone even if the clone occurs on a thread which doesn't have access to the span.
> Preserve Error's span thread id if cloned from a different thread

- src/error.rs
- src/thread.rs
This PR shrinks the size of ErrorMessage from 56 bytes to 40 bytes.
> Eliminate second redundant ThreadId from ErrorMessage

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- syn.json
- tests/debug/gen.rs
- tests/test_precedence.rs
> Delete GenericMethodArgument in favor of GenericArgument

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- src/path.rs
- syn.json
- tests/debug/gen.rs
Following #1320, these are practically equivalent pieces of syntax.
> Delete MethodTurbofish in favor of AngleBracketedGenericArguments

- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- src/lib.rs
- syn.json
- tests/debug/gen.rs
- tests/test_generics.rs
This syntax does not appear to be on track for stabilization. https://github.com/rust-lang/rust/issues/20041
> Delete WherePredicate::Eq and PredicateEq

- src/generics.rs
- syn.json
- tests/debug/gen.rs
- tests/test_generics.rs
Between equality constraints and "const if const" bounds and [contexts/capabilities](https://tmandry.gitlab.io/blog/posts/2021-12-21-context-capabilities/#scoped-bounds), it's unclear what might appear in `where`-predicates later.
> Make WherePredicate enum non-exhaustive

- src/lit.rs
- syn.json
- tests/debug/gen.rs
New kind of literal on the horizon: https://github.com/rust-lang/rfcs/pull/3348
> Make Lit enum non-exhaustive

- src/data.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- syn.json
- tests/debug/gen.rs
- tests/test_derive_input.rs
- tests/test_visibility.rs
https://github.com/rust-lang/rust/issues/53120
https://github.com/rust-lang/rust/pull/97239
> Delete Visibility::Crate and VisCrate

- src/item.rs
- tests/repo/mod.rs
https://github.com/rust-lang/rust/issues/89122
> Move GAT where-clause to after type, extern type to both

- src/attr.rs
- tests/test_attribute.rs
https://github.com/rust-lang/rfcs/pull/3325
> Parse unsafe attributes

- src/file.rs
Mostly I'm doing this to make `parse_file` easy to discover with rustdoc hyperlinks
> Add note to `File` rustdoc about `parse_file`.

- src/token.rs
This approach requires Rust 1.54+. Syn's oldest supported compiler previously was 1.31 so we weren't able to do it this way.
> Generate documentation for token types

- codegen/src/debug.rs
- src/gen/debug.rs
- src/lit.rs
**Before:**
```rust
Item::Fn(
ItemFn {
...
block: Block {
brace_token: Brace,
stmts: [
Stmt::Expr(
Expr::Path(
ExprPath {
...
```
**After:**
```rust
Item::Fn {
...
block: Block {
brace_token: Brace,
stmts: [
Stmt::Expr(
Expr::Path {
...
```
> More compact Debug representation for syntax tree enums

- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- src/lib.rs
- src/lookahead.rs
- src/parse.rs
- syn.json
- tests/debug/gen.rs
- tests/test_generics.rs
- tests/test_ty.rs
This name makes more sense in the context of then `GenericParam` enum, and is the name that the Rust Reference uses. 
```rust
pub enum GenericParam {
Type(TypeParam),
Lifetime(LifetimeParam),
Const(ConstParam),
}
```
https://doc.rust-lang.org/nightly/reference/items/generics.html
> Rename LifetimeDef -> LifetimeParam

- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- syn.json
- tests/debug/gen.rs
This matches the order in the Rust Reference. It also matches the order these parameters are *required* to appear in source code &mdash; makes sense.
https://doc.rust-lang.org/nightly/reference/items/generics.html
> Reorder GenericParams so lifetimes come before types

- src/generics.rs
- tests/repo/mod.rs
Rustc's parser allows `for<'a: 'b>` and rejects it later. We can reject until somebody has a  use case that requires being able to parse this pseudo-syntax.
> Do not parse bounds on lifetime as part of BoundLifetimes

- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/generics.rs
- syn.json
- tests/test_ty.rs
The Rust Reference allows `for<>` syntax to contain any generic param, not only lifetime params. https://doc.rust-lang.org/1.67.0/reference/trait-bounds.html#higher-ranked-trait-bounds
In a world of GATS getting more fleshed out I can easily see that syntax getting used eventually.&mdash;
```rust
trait Trait {
type Assoc<T>;
}
fn f<K>() where K: for<T> Trait<Assoc<T> = u8> {}
```
The type name `BoundLifetimes` is not great in that situation but it's better than breaking changes.
> Generalize BoundLifetimes to hold non-lifetime generic params

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- src/pat.rs
- syn.json
- tests/debug/gen.rs
Closes #1352.
According to https://doc.rust-lang.org/1.67.0/reference/patterns.html#tuple-patterns `(..)` is a special case and is a tuple, not paren pattern, even without trailing comma.
> Add a Pat variant for a single parenthesized pattern

- src/expr.rs
- src/pat.rs
- tests/repo/mod.rs
- tests/test_expr.rs
- tests/test_pat.rs
None of the following are valid expressions, but were previously accepted by syn.
- `..=`
- `lo..=`
- `...`
- `...hi`
- `lo...`
- `lo...hi`
None of the following are valid patterns, but were previously accepted by syn.
- `[lo..]`
- `[..=hi]`
> Stricter parsing of ranges

- src/lit.rs
- tests/test_lit.rs
According to https://doc.rust-lang.org/reference/tokens.html#string-literals
only these 4 characters are actually skipped.
> stricter parsing of string_continue escapes

- src/path.rs
- syn.json
- tests/debug/gen.rs
As one example, "compact notation" for "return type notation" would require a path argument that is not covered by any of the existing variants. https://smallcultfollowing.com/babysteps/blog/2023/02/13/return-type-notation-send-bounds-part-2/#more-compact-notation
> Make GenericArgument non-exhaustive

- src/punctuated.rs
I was briefly confused when I saw that it must push behind a trailing punctuation.
> doc: clarify that push_value can be used on empty Punctuated

- src/token.rs
To accommodate https://github.com/dtolnay/proc-macro2/pull/366. I'd like for `Brace` and `Bracket` and `Parenthesis` to be represented using `DelimSpan`, while keeping `Group` using only `Span`, as it does not have a meaningful open and close punctuation span.
> Move definition of syn::token::Group out of define_delimiters

- codegen/src/fold.rs
- codegen/src/visit.rs
- codegen/src/visit_mut.rs
- src/gen/fold.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/gen_helper.rs
From the lack of engagement in #462, I am skeptical that anyone really needs any of `fold_span`, `visit_span`, or `visit_span_mut`.
Closes #462.
> Delete Span methods from fold, visit, visit_mut

- src/buffer.rs
- src/parse.rs
The new implementation simply increments the reference count on the existing `Group` token's contents, instead of collecting a whole new `TokenStream`. It also preserves the ability to access a meaningful `span_open()` and `span_close()`, which is lost by `Group::new` / `set_span`.
> Optimize Parse for Group

- src/expr.rs
- tests/repo/mod.rs
Previously this would fail after trying to parse `await` as a `Member`.
```console
error: expected identifier or integer
--> dev/main.rs:5:22
|
5 |         let _ = x.0. await;
|                      ^^^^^
```
> Fix parsing of `x.0. await`

- src/lib.rs
- src/parse_quote.rs
This reverts https://github.com/dtolnay/syn/commit/491680abaa83ee01739262e387bb0e9a7e71b530. #512 made `parse_quote!` call `quote!` via a re-export located in the syn crate instead of directly unhygienically, and the re-export only exists if syn's "printing" feature is on.
> Do not provide a parse_quote macro when printing feature is off

- src/expr.rs
This syntax has been removed from rustc in https://github.com/rust-lang/rust/pull/108471.
`box` in pattern position is not affected.
> Delete parsing of box syntax in expression position

- src/attr.rs
This kind of thing. I'd want to be presented a compelling use case before allowing this.
```console
error: unexpected attribute inside of attribute
--> dev/main.rs:4:15
|
4 |     #[outer = #[inner] expr]
|               ^
```
> Disallow outer attribute on expr inside of attribute

- src/ident.rs
Before:
```console
error: expected identifier
--> dev/main.rs:4:8
|
4 |     fn async() {}
|        ^^^^^
```
After:
```console
error: expected identifier, found keyword `async`
--> dev/main.rs:4:8
|
4 |     fn async() {}
|        ^^^^^
```
This lines up with how Rust's error reporting in macro_rules handles the same situation.
```rust
macro_rules! path {
($p:path) => {};
}
path!(async);
```
```console
error: expected identifier, found keyword `async`
--> src/lib.rs:5:7
|
5 | path!(async);
|       ^^^^^ expected identifier, found keyword
```
> Improve error message when parsing Ident encounters keyword

- src/path.rs
Before:
```console
error: expected path
--> dev/main.rs:4:8
|
4 |     #![async]
|        ^^^^^
error: unexpected end of input, expected path segment
--> dev/main.rs:5:13
|
5 |     #![foo::]
|             ^
```
After:
```console
error: expected identifier, found keyword `async`
--> dev/main.rs:4:8
|
4 |     #![async]
|        ^^^^^
error: unexpected end of input, expected path segment after `::`
--> dev/main.rs:5:13
|
5 |     #![foo::]
|             ^
```
> Improve error reporting in path parser

- src/stmt.rs
Before:
```console
error: unexpected token
--> dev/main.rs:5:13
|
5 |         f() g()
|             ^
```
After:
```console
error: unexpected token, expected `;`
--> dev/main.rs:5:13
|
5 |         f() g()
|             ^
```
> Improve error message on missing `;` between statements

- src/stmt.rs
- tests/test_stmt.rs
Rust does not allow a stmt macro to be called with this syntax.
```rust
macro_rules! m {
() => {
struct S;
}
}
fn main() {
m!()
}
```
But if the call is written as `m!();` or `m! {}`, we'll continue to parse it as Stmt::Macro.
> Keep non-brace macro invocations in trailing expr position as Expr::Macro

- src/meta.rs
Before:
```console
error: unexpected end of input, unexpected token in nested attribute, expected ident
--> test_suite/tests/regression/issue2415.rs:4:9
|
4 | #[serde()]
|         ^
```
After:
```console
error: unexpected end of input, expected nested attribute
--> test_suite/tests/regression/issue2415.rs:4:9
|
4 | #[serde()]
|         ^
```
> Improve error message on empty parens inside parse_nested_meta

- src/expr.rs
Fixes #1433.
**`a.0.1` before:**
```rust
Expr::Field {
attrs: [],
base: Expr::Field {
attrs: [],
base: Expr::Path {
attrs: [],
qself: None,
path: Path {
leading_colon: None,
segments: [
PathSegment {
ident: Ident {
ident: "a",
span: #0 bytes(95..96),
},
arguments: PathArguments::None,
},
],
},
},
dot_token: Dot,
member: Member::Unnamed(
Index {
index: 0,
span: #5 bytes(0..102),
},
),
},
dot_token: Dot,
member: Member::Unnamed(
Index {
index: 1,
span: #5 bytes(0..102),
},
),
}
TokenStream [
Ident {
ident: "a",
span: #0 bytes(95..96),
},
Punct {
ch: '.',
spacing: Alone,
span: #0 bytes(96..97),
},
Literal {
kind: Integer,
symbol: "0",
suffix: None,
span: #5 bytes(0..102),
},
Punct {
ch: '.',
spacing: Alone,
span: #0 bytes(97..100),
},
Literal {
kind: Integer,
symbol: "1",
suffix: None,
span: …
```
> Improve spans of Expr::Field parsed from a float Literal

- json/Cargo.toml
`indexmap` 1.9.3 (latest release) and older auto-detect the use of std by testing whether the current toolchain is able to compile a probe file containing `extern crate std;`. If it fails, `IndexMap` does not default the third generic parameter, causing builds of syn-codegen to fail.
In indexmap master, this is fixed by defaulting the `std` feature.
> Force indexmap std support

- examples/dump-syntax/src/main.rs
Fixes #1445.
```console
error: Syn unable to parse file
--> test.rs:3:7
|
3 | fodd() {
|        ^ lex error
```
> Render zero sized spans in dump-syntax example

- json/src/lib.rs
This revision includes:
- Correct minor typo
- publicy -> publicly
> Correct minor typo

- Cargo.toml
- src/buffer.rs
- src/export.rs
- src/lib.rs
- src/parse.rs
See https://github.com/dtolnay/proc-macro2/pull/388.
> Extern crate proc_macro available on all wasm targets

- src/meta.rs
> Permit empty attr in syn::meta::parser

- src/error.rs
- src/thread.rs
The way #1315 was implemented is unsound if someone has a standard library implementation on which `proc_macro::Span`'s `Clone` impl is not just equivalent to its `Copy` impl, but involves accessing the span's thread-local data.
Reported by @joshlf.
> Fix call of proc_macro::Span::clone on the wrong thread

- src/error.rs
- This fixes the error message loss (shadowed by an error complaining about `::core` not found) for 2015 edition callers when the callee was using `Error::new_spanned` over the caller's input tokens (since this would then *resolve* `::core` using the caller's edition).
- an example:
```rs
error[E0433]: failed to resolve: unresolved import
--> /Users/cmdjojo/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.20/src/webcore/ffi/wasm_bindgen.rs:67:32
|
67 |             alloc: &Closure< Fn( usize ) -> *mut u8 >,
|                                ^ unresolved import
```
complains about `unresolved import` while pointing to an open parenthesis.
- More generally, it seems more conceptually correct to only be tweaking the `located_at` aspect of spans when dealing with a `compile_error!` …
> *Resolve* spanned errors at call/mixed site

- README.md
- examples/trace-var/README.md
- json/src/lib.rs
Hey @dtolnay, thanks for the contribution to the Rust community! :)
- Update legacy 1.0 docs.rs links and point it to latest `syn`
> Update docs.rs links to latest `syn`

- src/lit.rs
This applies the changes from #1381, which only touched string literals, to byte string literals as well.
```rust
println!("{:?}", syn::parse_str::<syn::LitByteStr>("b\"\\\n\x0b\x0c\x0a.\"").unwrap().value());
```
Before: `[46]`
Correct value: `[11, 12, 10, 46]`
> Stricter parsing of string_continue escape in cooked byte string literal

- src/item.rs
- src/stmt.rs
Previously, attributes would go missing, for example in the following case:
```rust
fn main() {
#[cfg(...)]
macro m() {...}
}
```
where there is `Stmt::Item` containing `Item::Verbatim`.
> Preserve attributes on verbatim Item in statement position

- src/expr.rs
This commonly comes up in array sizes, when working with const generic parameters computed from a type parameter.
```rust
#![feature(generic_const_exprs)]
struct Foo<T: strum::EnumCount>
where
[(); { T::COUNT }]:,
{
foo: heapless::Vec<u8, { T::COUNT }>,
}
```
We can't parse them as Expr::Block because that data structure contains a field of type Vec\<Stmt\>, and Stmt is "full"-only.
But parsing as Expr::Verbatim will at least allow this where-clause to round trip.
> Parse block expr as verbatim in non-full mode

- src/path.rs
Fixes https://github.com/serde-rs/serde/issues/2414.
In non-"full" mode, syn parses `Generic<{ BAR as u8 }>` with a GenericArgument::Const containing Expr::Verbatim (because the data structures for Expr::Block are not available). But then, it wrongly printed that out as `Generic<{ { BAR as u8 } }>`, leading to bogus warnings in generated code.
> Fix duplication of braces around const generic argument in non-full mode

- src/punctuated.rs
All of the types involved here (`Vec`, `Option`, `Box`) have optimized implementations of `clone_from`.
> Preserve existing allocations when cloning Punctuated

- src/ident.rs
Since https://github.com/rust-lang/rust/issues/105735 was fixed, this `cfg` is not necessary anymore.
> Remove unneeded cfg

- src/lib.rs
Consequence of https://github.com/rust-lang/rust/pull/112108.
> Fix useless re-exports section appearing in documentation at crate root

- src/expr.rs
This silly difference causes serde_derive's UI test suite to fail depending on whether syn's "full" feature is turned on.
https://github.com/dtolnay/syn/blob/f79ba1540239f29e82b3011295755270ef05f66e/src/expr.rs#L1666
https://github.com/dtolnay/syn/blob/f79ba1540239f29e82b3011295755270ef05f66e/src/expr.rs#L1692
```console
test tests/ui/malformed/cut_off.rs ... mismatch
EXPECTED:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: unexpected end of input, expected an expression
--> tests/ui/malformed/cut_off.rs:4:17
|
4 | #[serde(rename =)]
|                 ^
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
ACTUAL OUTPUT:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: unexpected end of input, expected expression
--> …
```
> Fix trivial difference between full and non-full expression parse errors

- src/export.rs
`std::primitive` has been stable since Rust 1.43.
> Switch to using primitives in macro-generated code through std::primitive

- src/path.rs
Parsing options inside a list is very commonplace:
```text
#[my_attr(path(linux = "path/to/file")]
^^^^ ^^^^^
Here is our options
```
Although we have `get_ident`, we (at least I) would not like to handle `None`. Just like `require_path`, `require_list` and `require_key_value`, which I love.
```rust
match &*path.require_ident()?.to_string() {
"linux" => { ... }
"windows" => { ... }
"macos" => { ... }
other => return Err(Error::new(
Span::call_site(),
format!("platform `{other}` not supported")
))
}
```
> Add `require_ident` to `Path`

- src/ident.rs
- src/lifetime.rs
- src/lit.rs
For some reason rustdoc is not respecting the `doc(hidden)` on these functions. See https://docs.rs/syn/2.0.27/syn/index.html#functions.
They were hidden correctly in https://docs.rs/syn/2.0.26/syn/index.html#functions so this must be related to #1490.
`cfg(doc)`/`cfg(not(doc))` is supported since Rust 1.41.
> Add `cfg(not(doc))` to `doc(hidden)` functions

- src/token.rs
This allows rust-analyzer to correctly complete the preferred brackets, instead of parenthesis.
https://github.com/rust-lang/rust-analyzer/issues/15608#issuecomment-1718821707
I wasn't sure what to put in there as the extensive documentation is at the module doc
>  Add example to `Token!` documentation

- src/ident.rs
- src/lifetime.rs
- src/lit.rs
- src/macros.rs
#1511 breaks the docs.rs doc build for [2.0.34](https://docs.rs/crate/syn/2.0.34/builds/912977) and [2.0.35](https://docs.rs/crate/syn/2.0.35/builds/913063). The documentation builds successfully as `cargo doc --all-features`, but not `RUSTDOCFLAGS='--generate-link-to-definition -Zunstable-options' cargo doc --all-features` as used by docs.rs.
> Work around doc breakage in generate-link-to-definition mode

- src/custom_punctuation.rs
This should solve the following error
```rs
error[E0053]: method `peek` has an incompatible type for trait
--> src/lib.rs:61:5
|
61 |     custom_punctuation!(Neq, <>);
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|     |
|     expected `bool`, found a different `bool`
|     help: change the output type to match the trait: `bool`
|
= note: expected signature `fn(syn::buffer::Cursor<'_>) -> bool`
found signature `fn(syn::buffer::Cursor<'_>) -> bool`
```
that occurs when trying to define
```rs
mod kw {
custom_token!(bool);
custom_punctuation!(Neq, <>);
}
```
> Absolute path to `bool` in `custom_punctuation.rs`

- src/expr.rs
- tests/repo/mod.rs
> More precise decision to parse expression after `return`, `break`, `yield`

- src/expr.rs
- tests/test_expr.rs
See https://github.com/rust-lang/rust/pull/87026.
Before:
```console
error: unexpected token, expected `;`
--> dev/main.rs:9:21
|
9 |         break 'label: loop { break 'label 42; };
|                     ^
```
After:
```console
error: parentheses required
--> dev/main.rs:9:15
|
9 |         break 'label: loop { break 'label 42; };
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
> Improve parsing of labeled loop as value expression for break

- src/expr.rs
- tests/test_stmt.rs
Previously, `loop {} ()` was correctly parsed as:
```rust
Stmt::Expr(
Expr::Loop {
body: Block,
},
None,
),
Stmt::Expr(
Expr::Tuple,
None,
),
```
but `'a: loop {} ()` was parsed incorrectly:
```rust
Stmt::Expr(
Expr::Call {
func: Expr::Loop {
label: Some(Label {
name: Lifetime {
ident: "a",
},
}),
body: Block,
},
},
None,
),
```
They both need to be parsed as `Expr::Loop` followed by `Expr::Tuple`.
> Fix parsing of labeled loop followed by paren in stmt or match arm position

- codegen/src/snapshot.rs
- tests/debug/gen.rs
- tests/test_asyncness.rs
- tests/test_generics.rs
- tests/test_item.rs
- tests/test_shebang.rs
- tests/test_stmt.rs
Just `block: Block` is disorienting. Render as `block: Block { stmts: [] }`.
> Include empty `stmts = []` in snapshots

- src/expr.rs
The infinite loop can be reproduced like this:
```rust
use proc_macro2::{Delimiter, Group};
use quote::quote;
fn main() {
let attr = Group::new(Delimiter::None, quote!(#[attr]));
let tokens = quote!(#attr 0);
syn::parse2::<syn::Expr>(tokens).unwrap();
}
```
The bug is from #853. Given nothing has hit this in 3.5 years, probably a group in that position does not need to be supported. But it should return an error instead of looping.
> Fix infinite loop on attr surrounded by None-delimited group

- src/expr.rs
- tests/test_expr.rs
Example of an input that previously behaved incorrectly:
```rust
let nested = Group::new(Delimiter::None, quote!(a::b || true));
let tokens = quote!(if #nested && false {});
syn::parse2::<syn::Expr>(tokens).unwrap()
```
**Before:** this has the wrong precedence. `a::b || (true && false)`
```rust
Expr::If {
cond: Expr::Binary {
left: Expr::Path {
path: Path {
segments: [
PathSegment {
ident: "a",
},
PathSegment {
ident: "b",
},
],
},
},
op: BinOp::Or,
right: Expr::Binary {
left: Expr::Lit {
lit: Lit::Bool {
value: true,
},
},
op: BinOp::And,
right: Expr::Lit {
lit: Lit::Bool {
value: false,
},
},
},
},
then_branch: Block {
stmts: [],
},
}
```
**After:** correct precedence. `(a::b || true) && false`
```rust
Expr::If {
cond: Expr::Binary {
left: Expr::Group {
expr: Expr::Binary {
left: …
```
> Support interpolated $:path followed by macro call or struct literal

- src/expr.rs
- tests/test_expr.rs
Example input: `$expr.method()` where expr is `&self`.
**Before:** incorrect, this is `&(self.method())`
```rust
Expr::Reference {
expr: Expr::MethodCall {
receiver: Expr::Path {
path: Path {
segments: [
PathSegment {
ident: "self",
},
],
},
},
method: "method",
},
}
```
**After:** correct. `(&self).method()`
```rust
Expr::MethodCall {
receiver: Expr::Group {
expr: Expr::Reference {
expr: Expr::Path {
path: Path {
segments: [
PathSegment {
ident: "self",
},
],
},
},
},
},
method: "method",
}
```
> Respect None-delimited group when parsing unary expr

- src/expr.rs
- tests/test_expr.rs
Previously `match v { _ => $expr }` with $expr=`loop {} + 1` would fail to parse, because the arm would get terminated after the `loop {}` and then `+ 1` would try to get parsed as a pattern.
> Fix stmt boundary after None-delimited group containing loop

- src/parse_quote.rs
- tests/test_parse_quote.rs
```rust
let field: Field = parse_quote!(pub enabled: bool);
```
> Support parsing Field in parse_quote

- src/buffer.rs
- src/lib.rs
This is allow-by-default for now in 2021 edition, but will become warn-by-default in 2024 edition.
> Turn on deny(unsafe_op_in_unsafe_fn)

- build.rs
Cargo guarantees that $RUSTC will be set for the build script. https://doc.rust-lang.org/1.75.0/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts
> Improve failure if cargo promised environment variable not present

- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/path.rs
- syn.json
This appears in derive input in the case of const associated functions.
```rust
#[derive(Derive)]
pub enum E {
V = CONFIG.compute_thing(),
}
struct Config { ... }
const CONFIG: Config = Config { ... };
impl Config {
const fn compute_thing(&self) -> isize { ... }
}
```
Previously with syn in non-"full" mode, a method call expression such as `CONFIG.compute_thing()` would parse incorrectly as Expr::Call containing Expr::Field as the called function, rather than Expr::MethodCall containing Expr::Path as the receiver.
> Make Expr::MethodCall available in non-"full" mode

- src/lib.rs
This regressed with https://github.com/rust-lang/rust/pull/113091 in nightly-2023-12-16. The doc(cfg()) from the type definition is no longer rendered.
> Restore doc cfg on re-exports

- src/data.rs
> Add a fallback for parsing DeriveInput discriminants to Verbatim in non-"full" mode

- src/pat.rs
This makes `PatType` work with `parse_quote!`. Useful for initializing the left-hand side of a `Local`, or a `FnArg::Typed`.
Closes #1554.
```rust
// [dependencies]
// syn = { version = "2", features = ["full", "extra-traits"] }
use syn::{parse_quote, PatType};
fn main() {
let pat: PatType = parse_quote! { ptr: usize };
println!("{:#?}", pat);
}
```
> Impl Parse for PatType

- src/expr.rs
This code needs to be shared between  `expr::parsing` and `expr::printing` in order to correctly do insertion of parentheses in `impl ToTokens for ExprBinary`. For now it's still `cfg(feature = "parsing")`, but it will be `cfg(any(feature = "parsing", feature = "printing"))`.
> Move expression Precedence enum to own module

- src/error.rs
This "lex error" message is from prior to https://github.com/rust-lang/rust/pull/68899 / https://github.com/dtolnay/proc-macro2/pull/265.
> Preserve LexError's Display representation in syn::Error

- src/expr.rs
- src/item.rs
- src/pat.rs
- src/ty.rs
> Pick up changes to non_exhaustive_omitted_patterns lint

- src/lit.rs
- src/parse.rs
I noticed this in https://github.com/colin-kiegel/rust-derive-builder/pull/310. When using `litstr.parse()` on a string literal token whose contents are empty, there previously were not any tokens in which the span could be transferred to the inner parser. This is what the "scope" span is supposed to be for, which is also used for parsing the contents of empty delimiters, for the same reason.
**Before:**
```console
error: unexpected end of input, expected expression
--> tests/compile-fail/deny_empty_default.rs:6:10
|
6 | #[derive(Builder)]
|          ^^^^^^^
|
= note: this error originates in the derive macro `Builder` (in Nightly builds, run with -Z macro-backtrace for more info)
```
**After:**
```console
error: unexpected end of input, expected expression
--> …
```
> Improve error location at eof in LitStr::parse

- src/parse.rs
> Implement Copy and ToTokens for Nothing

- tests/test_visibility.rs
> Add test of unnamed tuple struct field with inherited visibility

- src/custom_keyword.rs
- src/custom_punctuation.rs
`syn::custom_keyword!` produces potentially unused code if syn's "printing" feature is off, so that a ToTokens impl is not being generated.
This warning is new in nightly-2024-03-24 from https://github.com/rust-lang/rust/pull/119552.
```console
warning: field `span` is never read
--> src/custom_keyword.rs:94:17
|
94   |             pub span: $crate::__private::Span,
|                 ^^^^
|
::: src/expr.rs:1079:32
|
1079 |         crate::custom_keyword!(builtin);
|         -------------------------------
|         |                      |
|         |                      field in this struct
|         in this macro invocation
|
= note: `#[warn(dead_code)]` on by default
= note: this warning originates in the macro `crate::custom_keyword` (in Nightly builds, run with -Z macro-backtrace for …
```
> Suppress dead code lint on custom token's span field

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- tests/crate/Cargo.toml
- tests/crate/test.rs
This serves as an alternative to https://github.com/dtolnay/syn/commit/0b2b498fa5d48c4ae78c9dbe6f73423c209d87c8.
> Restore compatibility with rustc 1.56 through 1.59

- src/custom_punctuation.rs
Fixes #1609.
This didn't used to work prior to Rust 1.17 &mdash; see the contortions required for `Token![$]` in https://github.com/dtolnay/syn/commit/2ccec118ceb77479e3f7cbd5d79b75ba1b6e098c. But now there is no reason it shouldn't be supported.
> Support '$' in custom_punctuation macro

- codegen/Cargo.toml
- codegen/src/version.rs
Serde_derive enables syn's "clone-impls" feature, which is based on code that is generated by this codegen code. If syn's codegen depends on serde_derive, that means generated Clone impls need to be manually updated when making syntax tree changes. If codegen can avoid depending on "clone-impls", then the Clone impls can be generated.
> Remove codegen's dependency on serde_derive

- codegen/Cargo.toml
- codegen/src/main.rs
It takes 2 steps: `cargo run --no-default-features` to regenerate the Clone impls in src/gen/clone.rs, then `cargo run` (which depends on exactly those Clone impls through serde_derive) to regenerate syn.json.
> Support regenerating Clone impls with syntax tree changes

- .github/workflows/ci.yml
The Miri job is our slowest CI job. We get good enough coverage for the rustdoc tests in the nightly cron job; they do not also need to be tested in pull requests.
> Skip doctests in Miri job on pull requests

- src/lit.rs
`'\x80'` is not allowed (proc-macro2 already enforces this).
```console
error: out of range hex escape
--> src/main.rs:2:14
|
2 |     let _ = '\x80';
|              ^^^^ must be a character in the range [\x00-\x7f]
```
> Fix maximum allowed \x escape in character literal

- tests/repo/mod.rs
Without this, rustc's parser fails to parse files containing C-string literal syntax (https://github.com/dtolnay/syn/issues/1502). For example this file: <https://github.com/rust-lang/rust/blob/1.77.0/src/tools/clippy/tests/ui/needless_raw_string_hashes.rs>. In edition 2018, it fails with this error:
```console
error: unknown character escape: `a`
--> src/main.rs:13:10
|
13 |     cr#"\aaa"#;
|          ^ unknown character escape
|
= help: for more information, visit <https://doc.rust-lang.org/reference/tokens.html#literals>
help: if you meant to write a literal backslash (perhaps escaping in a regular expression), consider a raw string literal
|
13 |     cr#r"\aaa"#;
|        ~~~~~~~
error: unknown start of token: \
--> src/main.rs:19:9
|
19 |         \a
|         ^
error[E0765]: …
```
> Raise default edition of rust-lang/rust test files to 2021

- src/error.rs
- tests/test_grouping.rs
- tests/test_item.rs
- tests/test_lit.rs
- tests/test_parse_buffer.rs
- tests/test_pat.rs
- tests/test_path.rs
- tests/test_stmt.rs
- tests/test_ty.rs
- tests/test_visibility.rs
The IntoIterator impl for arrays was stabilized in Rust 1.53, whereas these days syn requires 1.60+.
> Take advantage of the IntoIterator for [T; N]

- src/pat.rs
The `Ident::parse_any` in this code is here to support https://github.com/dtolnay/syn/issues/517 in syn 0.15. At the time, the function argument in `fn f(self: T)` was parsed as https://docs.rs/syn/0.15.44/syn/enum.FnArg.html#variant.Captured in the form of a Pat, colon token, and Type. The only other variants of `FnArg` held a Pat only, a Type only, `self`, `mut self`, `&self`, or `&mut self`, none of which are suitable for the form `self: T`. So `self` needed to be handled as some kind of Pat, and Pat::Ident was selected. (It might alternatively have been Pat::Path.)
These days in syn 2, the function argument in `fn f(self: T)` is parsed as https://docs.rs/syn/2/syn/struct.Receiver.html but `self` continues to be considered a legal Pat::Ident. Keywords other than `self` should not be, …
> Check for legal binding name in the ident of Pat::Ident

- build.rs
- src/lib.rs
Context: https://blog.rust-lang.org/2024/05/06/check-cfg.html
> Resolve unexpected_cfgs warning

- src/expr.rs
- tests/test_expr.rs
Previously, syn incorrectly accepted `.. $e ..` as:
```rust
Expr::Range {
limits: RangeLimits::HalfOpen,
end: Some(Expr::Range {
start: Some($e),
limits: RangeLimits::HalfOpen,
}),
}
```
and `$e .. $e ..` as:
```rust
Expr::Range {
start: Some(Expr::Range {
start: Some($e),
limits: RangeLimits::HalfOpen,
end: Some($e),
}),
limits: RangeLimits::HalfOpen,
}
```
but these are not legal expressions in Rust. A range with a lower bound cannot be the upper bound of another range, and a range with an upper bound cannot be the lower bound of another range.
```console
error: expected one of `.`, `;`, `?`, `else`, or an operator, found `..`
--> src/main.rs:2:19
|
2 |     let _ = .. () ..;
|                   ^^ expected one of `.`, `;`, `?`, `else`, or an operator
error: expected one of `.`, `;`, …
```
> Disallow range with upper bound in lhs of binop

- src/expr.rs
- tests/test_expr.rs
Previously, syn incorrectly accepted `$a == $b == $c` as an expression:
```rust
Expr::Binary {
left: Expr::Binary {
left: $a,
op: BinOp::Eq,
right: $b,
},
op: BinOp::Eq,
right: $c,
}
```
but this is not a legal expression in Rust. The expression either needs to be parenthesized (`($a == $b) == $c` or `$a == ($b == $c)`) or turned into a conjunction (`$a == $b && $b == $c`).
```console
error: comparison operators cannot be chained
--> src/main.rs:2:18
|
2 |     let _ = true == true == true;
|                  ^^      ^^
|
help: split the comparison into two
|
2 |     let _ = true == true && true == true;
|                          +++++++
```
> Require parens for chained comparison binops

- src/parse.rs
- tests/test_parse_buffer.rs
ParseBuffer contains interior mutability, but there isn't any way to get it into some invalid state by panicking in user code.
> Make ParseBuffer unwindsafe

- src/classify.rs
- src/expr.rs
- src/lib.rs
- src/stmt.rs
This will eventually hold all 3 of the functions from <https://github.com/rust-lang/rust/pull/119427>'s compiler/rustc_ast/src/util/classify.rs:
- `expr_requires_semi_to_be_stmt`
- `expr_requires_comma_to_be_match_arm`
- `expr_trailing_brace`
> Create a module for expr classification functions

- src/classify.rs
- src/item.rs
- src/mac.rs
- src/stmt.rs
Context:
- https://github.com/rust-lang/rust/issues/119057
- https://github.com/rust-lang/rust/pull/119062
> Enforce that let-else's expression does not end in brace

- src/expr.rs
- src/lib.rs
- src/precedence.rs
As part of porting https://github.com/rust-lang/rust/pull/124191 to syn, a new `fixup` module is going to need access to some new precedence-related computations. Having a module dedicated to `precedence` will serve as a good location to have these.
> Extract Precedence to its own module

- src/path.rs
Previously, if you created a GenericArgument::Const containing an expression that was not legal syntax within a path's const generics, such as:
```rust
impl Trait<1 + 1>
^^^^^
```
then Syn would automatically legalize it in the ToTokens impl to print with braces: `impl Trait<{1 + 1}>`. But for GenericArgument::AssocConst it was not doing this, although the syntax rules are the same.
```rust
impl Trait<ASSOC = 1 + 1>
^^^^^
> Add legalization for expressions inside AssocConst

- src/generics.rs
- src/path.rs
Very similar to #1654, but for default values in the definition of a const generic parameter.
```rust
trait Trait<const K: usize = 1 + 1> {}
^^^^^
```
> Apply const argument legalization to default value of ConstParam

- src/expr.rs
In both `while break S {} {}` and `while return S {} {}`, the value broken/returned is parsed as `S {}` by rustc, not just `S`. In other words whether or not `allow_struct` is true outside of the break/return expression, inside it's treated as true regardless.
> Parse struct expressions eagerly within break and return

- src/classify.rs
- src/expr.rs
- src/stmt.rs
Ported from https://github.com/rust-lang/rust/pull/119427.
> Differentiate statement boundary rules for stmt vs match arm

- src/expr.rs
If a closure has an omitted return type, any kind of expression is allowed in the closure body: `|| 1 + 1`. But if there is a return type, only a block expression is allowed: `|| -> i32 { 1 + 1 }`. Without braces `|| -> i32 1 + 1` is not legal syntax.
> Create braces around closure body during printing if needed

- src/classify.rs
- src/expr.rs
- src/fixup.rs
- src/generics.rs
- src/lib.rs
- src/precedence.rs
- src/stmt.rs
- tests/test_expr.rs
Ported in large part from these rustc PRs:
- https://github.com/rust-lang/rust/pull/119105
- https://github.com/rust-lang/rust/pull/118726
- https://github.com/rust-lang/rust/pull/124191
> Automatically insert necessary parentheses in ToTokens for Expr

- codegen/src/fold.rs
- src/gen/fold.rs
- src/gen_helper.rs
`cargo llvm-lines | head`
```rust
use std::mem::{self, size_of};
use syn::fold::Fold;
use syn::{File, Ident};
struct MyFold;
impl Fold for MyFold {
fn fold_ident(&mut self, i: Ident) -> Ident {
println!("{}", i);
i
}
}
fn main() {
let file: File = unsafe { mem::transmute([1usize; size_of::<File>() / size_of::<usize>()]) };
MyFold.fold_file(file);
}
```
**Before:**
```console
Lines                 Copies              Function name
-----                 ------              -------------
101619                2821                (TOTAL)
25088 (24.7%, 24.7%)   98 (3.5%,  3.5%)  alloc::vec::in_place_collect::from_iter_in_place
11858 (11.7%, 36.4%)   98 (3.5%,  6.9%)  core::iter::traits::iterator::Iterator::try_fold
6370 (6.3%, 42.6%)    98 (3.5%, 10.4%) …
```
> Generate fewer monomorphizations in Fold

- codegen/src/fold.rs
- src/gen/fold.rs
- src/gen_helper.rs
- src/punctuated.rs
Vec's `into_iter`/`map`/`collect` has an optimization to run in-place if the original and mapped type are the same size and alignment, which is always the case for fold.
> Optimize punctuated::fold

- src/expr.rs
`let` is not valid as an expression on its own:
```rust
macro_rules! expr {
($e:expr) => {};
}
expr!(let _ = Struct {});
```
```console
error: no rules expected the token `let`
--> src/lib.rs:4:7
|
1 | macro_rules! expr {
| ----------------- when calling this macro
...
4 | expr!(let _ = Struct {});
|       ^^^ no rules expected this token in macro call
```
It is only allowed in combination with something like `if let …` or `while let …` or `if foo() && let …`, and none of those allow `{` in the `let` expression.
But `match … { … if let … => … }` (match guards) does allow it.
Closes #1670.
> Allow braced structs when parsing ExprLet

- Cargo.toml
This enables cross-compilation of tests with Miri, which previously failed due to the transitive dependency on `openssl-sys` through `reqwest`.
```console
$ cargo miri test --all-features --target i686-unknown-linux-gnu --test test_parse_buffer
error: failed to run custom build command for `openssl-sys v0.9.102`
Caused by:
process didn't exit successfully: `target/miri/debug/build/openssl-sys-908aa9a24708f521/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
I686_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
I686_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset …
```
> Prune dev-dependencies when testing with miri

- src/buffer.rs
- src/discouraged.rs
- src/group.rs
Fixes #1678.
The original implementation using `close_span_of_group` is significantly older than #1393, but as of the conversion to `DelimSpan`, this case is easy to handle correctly.
> Use span from the correct Group token when parsing delimited content

- src/buffer.rs
Example:
```rust
// src/main.rs
repro::repro!([1]);
fn main() {}
```
```rust
// src/lib.rs
use proc_macro::TokenStream;
use syn::parse::{Error, ParseStream, Result};
use syn::{bracketed, parse_macro_input};
fn parse(input: ParseStream) -> Result<()> {
let bracketed;
bracketed!(bracketed in input);
bracketed.step(|cursor| {
let mut cursor = *cursor;
while let Some((_literal, rest)) = cursor.literal() {
cursor = rest;
}
Err(Error::new(cursor.span(), "literal parser is insatiable"))
})
}
#[proc_macro]
pub fn repro(input: TokenStream) -> TokenStream {
parse_macro_input!(input with parse);
TokenStream::new()
}
```
Diagnostic before this PR: no indication of where in the input we were parsing.
```console
error: literal parser is insatiable
--> src/main.rs:3:1
|
3 | repro::repro!([1]);
| …
```
> Improve span returned by Cursor::span at end of a Group's contents

- src/token.rs
Previously `input.peek(syn::LitStr)` worked but `input.peek(syn::LitCStr)` would fail to compile.
```console
error[E0277]: the trait bound `LitCStr: CustomToken` is not satisfied
--> src/lib.rs:7:19
|
7   |     if input.peek(syn::LitCStr) {
|              ---- ^^^^^^^^^^^^ the trait `CustomToken` is not implemented for `LitCStr`, which is required by `fn(syn::lookahead::TokenMarker) -> LitCStr {LitCStr}: Peek`
|              |
|              required by a bound introduced by this call
|
= help: the following other types implement trait `CustomToken`:
syn::expr::parsing::kw::builtin
syn::expr::parsing::kw::raw
syn::ext::private::IdentAny
= note: required for `LitCStr` to implement `Token`
= note: required for `fn(syn::lookahead::TokenMarker) -> LitCStr {LitCStr}` to implement `Peek`
note: …
```
> Make LitCStr peekable

- src/ext.rs
- src/ident.rs
- src/lifetime.rs
- src/lit.rs
- src/lookahead.rs
- src/sealed.rs
- src/token.rs
> List peekable token types in documentation of Peek trait

- .github/workflows/ci.yml
- Cargo.toml
- README.md
I need this in an upcoming PR for access to `Vec::retain_mut`.
> Raise required compiler to rust 1.61

- src/token.rs
The `Literal` case is possible to optimize since https://github.com/dtolnay/syn/commit/66cb0c4381b0faaf1cf00f486f079338366461d5 (`Cursor::lifetime`), and the `Group` case since #1371 (`Cursor::any_group`). The original peek implementations pre-date those additions to the `Cursor` API.
> Optimize the peek impl of Group and Lifetime

- src/lit.rs
- src/token.rs
Prior to #1687, this `impl_token!` macro used to be shared in common between `Lit*` and `Lifetime` and `Group`, but now it is specific to just literals.
> Relocate `Lit` peek impls into `lit` module

- src/parse_quote.rs
When `parse_quote!` fails, show the location in user crate, not in `syn`.
> track-caller in quote_spanned!

- src/classify.rs
- src/expr.rs
- tests/test_expr.rs
Previously, it was possible for ExprBreak's ToTokens impl to produce `break 'inner: loop { break 'inner 1 } + 1` which is not valid Rust syntax.
Same bug in rustc: https://github.com/rust-lang/rust/pull/126883
> Parenthesize break values containing leading label

- src/punctuated.rs
> Add Punctuated::get and get_mut

- src/expr.rs
- src/fixup.rs
- src/precedence.rs
- tests/test_expr.rs
Previously, in `$a + 1` where $a is something like `1 + || 1` or `1 + return 1` or `1 + break 1` or `1 + ..=1`, the middle expression was not being adequately parenthesized to  preserve its precedence relative to the trailing `+ 1`.
> Parenthesize closures and jumps which are not rightmost subexpressions

- src/expr.rs
- src/fixup.rs
- src/precedence.rs
- tests/test_expr.rs
Previously syn would forcibly put parentheses when printing something like `(break) + 1` or `(return) + 1`. Although parentheses are required in `(break) - 1` and `(return) - 1`, they should not be required when the next token following the valueless jump is not a legal first token of an expression.
> Improve precision of jump parentheses when next token cannot begin expr

- src/fixup.rs
- src/precedence.rs
As of #1696, `Any` is no longer doing double duty to mean both "the minimum precedence" in the parser and "the precedence of jumps" in the printer.
> Improve name of precedence variant for jumps

- src/expr.rs
- tests/test_expr.rs
Unparenthesized ranges are legal on the right of an assignment, but not on the left of an assignment.
```console
error: expected one of `;` or `}`, found `=`
--> src/main.rs:3:12
|
3 |         .. = true;
|            ^ expected one of `;` or `}`
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `=`
--> src/main.rs:6:14
|
6 |         a..b = true;
|              ^ expected one of 8 possible tokens
```
> Parenthesize ranges on left-hand side of assignment operator

- src/expr.rs
- tests/test_expr.rs
`a < b < c` is not valid syntax. Depending on whether the inner comparison is on the left or right of the outer one, syn needs to insert parentheses to print either `(a < b) < c` or `a < (b < c)`.
> Parenthesize chained comparison on both sides

- src/fixup.rs
- tests/test_expr.rs
Printing Expr::Let at the start of a statement would cause it to be interpreted as Stmt::Local. This PR causes parentheses to be inserted in that scenario to preserve the Expr::Let.
> Parenthesize leading Expr::Let in statement

- src/expr.rs
- src/fixup.rs
- src/precedence.rs
This follows the strategy introduced by #1694 for jumps.
> Create a new precedence level for Expr::Let

- src/classify.rs
- src/expr.rs
- src/fixup.rs
- src/lib.rs
This is needed after https://github.com/dtolnay/syn/pull/1703 to support parenthesization of casts such as `1 + (x as i32) < 0`, which can occur even when "full" feature is not enabled.
> Enable expression fixups in "derive" mode

- src/punctuated.rs
Just removing the mutable requirement for `Puntuacted::get()`, probably a typo.
> Remove mut from Puntuated::get()

- src/generics.rs
- tests/test_ty.rs
Parses the new `use<>` precise capturing bound (https://rust-lang.github.io/rfcs/3617-precise-capturing.html) as verbatim in all bound positions.
Not exactly sure what the process is for syn support for nightly features. I could alternatively prepare a PR adding full support for this.
cc https://github.com/rust-lang/rust/issues/123432
> Parse `use<'a, T>` precise capturing bounds as verbatim

- src/buffer.rs
- src/discouraged.rs
- src/parse.rs
**Before:**
```console
error: unexpected token
--> dev/main.rs:4:22
|
4 |     extern fn f(..., more: T) {}
|                      ^^^^
```
**After:**
```console
error: unexpected token, expected `)`
--> dev/main.rs:4:22
|
4 |     extern fn f(..., more: T) {}
|                      ^^^^
```
> Include expected close delimiter in unexpected token message

- src/data.rs
Acts like `Fields::iter`, but map its `Field` items to `Member`.
For instance, in this struct
```rust
struct Foo {
a: f32,
b: bool
}
```
We use `iter_member` to access its fields, and implement `Clone` for it.
```rust
let fields: Fields = ...;
let idents = fields.iter().map(|f| &f.ident);
let members = fields.iter_member();
quote! {
impl Clone for Foo {
fn clone(&self) -> Self {
Self {
#(#idents: self.#members.clone(),)*
}
}
}
}
```
Then it generates
```rust
impl Clone for Foo {
fn clone(&self) -> Self {
Self {
a: self.a.clone(),
b: self.b.clone(),
}
}
}
```
There is a similar effect on unnamed fields in which iterates `Member::Index` instead.
> Add `Fields::iter_member`

- src/data.rs
- src/generics.rs
- src/macros.rs
- tests/test_iterators.rs
Fixes #1718.
There is no syntax in `impl Trait<'a>` to express that the underlying type either does not have a `Drop` impl or has a dropck eyepatch: `unsafe impl<#[may_dangle] 'a> Drop`.
> Expose non-impl-Trait iterator return types

- src/attr.rs
- src/expr.rs
- src/item.rs
- src/mac.rs
- src/pat.rs
- src/path.rs
- src/restriction.rs
- src/ty.rs
> Insert turbofish into paths in expression position

- src/expr.rs
This was probably written just mirroring the grammar of `return`. But for `become`, the expression after the keyword is mandatory.
```rust
#![allow(incomplete_features)]
#![feature(explicit_tail_calls)]
fn repro() {
become;
}
```
```console
error: expected expression, found `;`
--> src/lib.rs:5:11
|
5 |     become;
|           ^ expected expression
```
> Make tail call expr mandatory

- src/expr.rs
- tests/test_expr.rs
> Force cursor to advance in parse_expr calls

- tests/test_asyncness.rs
- tests/test_attribute.rs
- tests/test_derive_input.rs
- tests/test_expr.rs
- tests/test_generics.rs
- tests/test_grouping.rs
- tests/test_item.rs
- tests/test_meta.rs
- tests/test_parse_quote.rs
- tests/test_pat.rs
- tests/test_path.rs
- tests/test_receiver.rs
- tests/test_shebang.rs
- tests/test_stmt.rs
- tests/test_token_trees.rs
- tests/test_ty.rs
- tests/test_visibility.rs
As of https://github.com/mitsuhiko/insta/pull/540 and https://github.com/mitsuhiko/insta/pull/603, `cargo insta accept` writes fewer `###` in its raw string literals than it used to.
> Update insta inline snapshot delimiters

- src/classify.rs
- src/expr.rs
- src/gen/clone.rs
- src/gen/debug.rs
- src/gen/eq.rs
- src/gen/fold.rs
- src/gen/hash.rs
- src/gen/visit.rs
- src/gen/visit_mut.rs
- src/lib.rs
- src/precedence.rs
- src/stmt.rs
- src/token.rs
- syn.json
- tests/debug/gen.rs
- tests/test_precedence.rs
- tests/test_stmt.rs
`&raw const place` / `&raw mut place` syntax is stabilizing in Rust 1.82.
> Add Expr::RawAddr

- src/generics.rs
- src/item.rs
- src/path.rs
- src/ty.rs
Syntax like `let _: &dyn ~const Trait` and `trait Alias<'a> = use<'a> + Trait` are not allowed.
> Reject precise captures and ~const in inappropriate syntax positions

- src/generics.rs
This matches how we already reorder lifetimes inside angle bracketed generic path arguments and generic params.
https://github.com/dtolnay/syn/blob/b3872490b08c3487a9ae243626ccac8008b7685b/src/path.rs#L808-L809
https://github.com/dtolnay/syn/blob/b3872490b08c3487a9ae243626ccac8008b7685b/src/generics.rs#L1096-L1097
https://github.com/dtolnay/syn/blob/b3872490b08c3487a9ae243626ccac8008b7685b/src/generics.rs#L1130-L1131
https://github.com/dtolnay/syn/blob/b3872490b08c3487a9ae243626ccac8008b7685b/src/generics.rs#L1182-L1183
> Reorder precise captured params to print lifetimes before idents

- codegen/src/fold.rs
- codegen/src/visit_mut.rs
- src/gen/fold.rs
- src/gen/visit_mut.rs
> Add Fold and VisitMut methods for Vec<Attribute>

- src/expr.rs
`custom_keyword!` expands to more code than we need in this use case, including Clone and Debug and ToTokens impls which are all unused.
> Reduce use of custom_keyword for parsing builtin expr

- Cargo.toml
- codegen/Cargo.toml
- codegen/src/css.rs
- codegen/src/main.rs
- src/gen/token.css
| Before | After |
|---|---|
| <p><img src="https://github.com/user-attachments/assets/f0051149-9ae7-446c-a2a9-f0f5318fe0d1" width="360"><br> | <p><img src="https://github.com/user-attachments/assets/e4d5f8a7-c24c-42ea-912d-9beb2b212ff0" width="360"><br> |
> Render token type names using `Token!` macro in documentation

- src/item.rs
- tests/repo/mod.rs
Closes https://github.com/dtolnay/syn/issues/1675.
> Parse safe and explicitly unsafe extern items

- src/item.rs
```rust
unsafe extern {
pub unsafe static STATIC: T;
}
```
Fixes a bug in #1768.
> Preserve extern static unsafety in ForeignItem::Verbatim

- src/parse_quote.rs
`parse_quote!` for a single Attribute was already supported since #319.
```rust
self.attrs.push(parse_quote! {
#[...]
});
```
This PR adds support for:
```rust
self.attrs = parse_quote! {
#[...]
#[...]
};
```
```rust
self.attrs.append(&mut parse_quote! {
#[...]
#[...]
});
```
> Allow `parse_quote!` to produce Vec<Attribute>

- src/lookahead.rs
- src/parse.rs
> Support peeking End

- src/data.rs
https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html#native-syntax-for-creating-a-raw-pointer
```rust
static X: i32 = 0;
pub enum Enum {
Variant = match &raw const X { _ => 1 },
}
```
> Parse raw addr syntax in discriminants

- src/precedence.rs
- tests/test_expr.rs
`thing.field` does not need parentheses around `thing`, but `(#[attr] thing).field` does. So the presence of outer attributes is relevant to the effective precedence of a subexpression.
> Lower the precedence of expressions containing outer attrs

- src/expr.rs
- tests/test_expr.rs
`(thing.field)()` is not equivalent to `thing.field()`.
But `(thing.0)()` and `thing.0()` _are_ equivalent.
> Fix parenthesization of field expressions in function calls

- src/expr.rs
- src/fixup.rs
- tests/test_expr.rs
Previously, the syntax tree for `(return)..=return` (with paren flattened away) would get incorrectly turned into `return ..=return` which means a different thing.
> Fix parenthesization of jumps in ranges

- src/expr.rs
- src/fixup.rs
The logic in this function, notably the treatment of `next_operator_can_begin_expr` and `next_operator_can_continue_expr` and `next_operator_can_begin_generics`, only makes sense if the subexpression's last token is the same as the outer expression's last token.
> Rename subsequent_subexpression -> rightmost_subexpression

- src/classify.rs
Simpler than https://github.com/dtolnay/syn/pull/1808.
> Recursive implementation of confusable_with_adjacent_block

- src/classify.rs
- tests/test_expr.rs
This fixes some false positives in parenthesis insertion.
> Tweak block confusable logic for labeled blocks

- src/stmt.rs
For the program `fn main() { m! {} .. }`, Syn would previously parse this as `[Stmt::Expr(Expr::Range { start: Expr::Macro, end: None })]`. The correct parse is `[Stmt::Macro, Stmt::Expr(Expr::Range { start: None, end: None })]` as is clear from the following diagnostic from rustc.
```console
error[E0308]: mismatched types
--> src/main.rs:1:19
|
1 | fn main() { m! {} .. }
|          -        ^^ expected `()`, found `RangeFull`
|          |
|          expected `()` because of default return type
```
> Fix incorrect parse of statement macro followed by range

- src/expr.rs
- tests/test_expr.rs
Expressions like `return .. .field` were being parsed correctly, but `return .. ?` was not.
> Add tests of bailout involving ranges and dots, and fix for question

- src/expr.rs
- tests/test_expr.rs
Syn failed to parse expressions like `return .. = x`, although this is considered valid syntax by rustc. The precedence is `(return ..) = x` to conform with the rule that a range expression cannot appear in the direct left operand of an assignment.
> Fix ranges bailout edge cases with assignment

- src/expr.rs
- src/fixup.rs
The latter is not used commonly enough to get a separate method with a shorter name.
> Merge leftmost_subexpression_with_operator and leftmost_subexpression into one method

- src/fixup.rs
This makes a difference for expressions such as `*(&(x as T)..)` (unary deref containing range containing reference containing cast). Without this, it would get printed incorrectly as `*(&x as T..)` (unary deref containing range containing cast containing reference).
> Disambiguate Expr::Cast precedence in scan_left

- src/fixup.rs
This will generalize better to expressions containing `let`.
> Choose range bailouts based on precedence

- src/fixup.rs
This part of rightmost_subexpression_precedence is deciding whether to raise the precedence of a low-precedence expression because the parenthesis's role is instead going to be served by a bailout. But when the caller was not planning to put parentheses anyway, computing a completely accurate precedence is unnecessary work.
> Short-circuit precedence scan for high-precedence expressions

- src/parse.rs
- src/punctuated.rs
Example:
```rust
use syn::parse::{ParseBuffer, ParseStream, Result};
use syn::token::{Brace, Bracket, Paren};
use syn::{braced, bracketed, parenthesized, MacroDelimiter};
fn parse(input: ParseStream) -> Result<()> {
let (_delim, _content) = input.call(macro_delimiter)?;
Ok(())
}
fn macro_delimiter<'a>(input: ParseStream<'a>) -> Result<(MacroDelimiter, ParseBuffer<'a>)> {
let content;
let lookahead = input.lookahead1();
let delim = if input.peek(Paren) {
MacroDelimiter::Paren(parenthesized!(content in input))
} else if input.peek(Brace) {
MacroDelimiter::Brace(braced!(content in input))
} else if input.peek(Bracket) {
MacroDelimiter::Bracket(bracketed!(content in input))
} else {
return Err(lookahead.error());
};
Ok((delim, content))
}
```
**Before:**
```console
error[E0308]: mismatched …
```
> Allow lifetimes in function pointer return values

- src/generics.rs
I'd like to write something like this:
```rust
struct W(syn::Generics);
impl W {
pub fn as_turbofish(&self) -> syn::Turbofish<'_> {
self.0.split_for_impl().1.as_turbofish()
}
}
```
Unfortunately, that doesn't compile today and as far as I can tell it's completely unimplementable -
the lifetime of the `syn::Turbofish` ends up tied to the temporary returned by `split_for_impl`.
That seems silly and unintentional, fix it.
> Fix lifetime on `as_turbofish`

- src/stmt.rs
Include a semicolon in `syn::Local`’s doc comment example to better reflect the struct fields.
> Include semicolon in doc comment example for `syn::Local`.

- tests/repo/mod.rs
Closes https://github.com/dtolnay/syn/issues/1894. Closes https://github.com/dtolnay/syn/issues/1885.
These were both fixed by the 3rd commit of #1897.
> Enable more const trait tests

- src/generics.rs
- tests/repo/mod.rs
- tests/test_generics.rs
Corresponding rustc change: https://github.com/rust-lang/rust/pull/127054
> Reject polarity modifier and lifetime binder used in the same trait bound

- src/generics.rs
- tests/repo/mod.rs
Closes https://github.com/dtolnay/syn/issues/1435.
Const parameters continue to be unsupported, like in rustc.
```rust
#![feature(non_lifetime_binders)]
pub trait Trait<const K: usize> {}
pub fn f<T>()
where
T: for<const K: usize> Trait<K>,
{}
```
```console
error: late-bound const parameters cannot be used currently
--> src/lib.rs:7:18
|
7 |     T: for<const K: usize> Trait<K>,
|                  ^
```
> Parse type parameter binder

- tests/repo/mod.rs
The rustc bug was solved by https://github.com/rust-lang/rust/pull/132088.
> Re-enable test of unsafe extern statics

- src/generics.rs
- tests/repo/mod.rs
This seems harmless to allow syntactically. Rustc does as well, since Rust 1.51:
```rust
pub trait Trait<const K: usize> {}
#[cfg(any())]
fn f(_: impl for<const K: usize> Trait<K>) {}
```
> Allow const parameters in for<>

- src/expr.rs
- src/generics.rs
- src/item.rs
This is part of the work required for https://github.com/dtolnay/syn/issues/1906.
> Synchronize generics-vs-qpath heuristic with rust parser

- codegen/src/parse.rs
This used to be used elsewhere prior to 11c68a39f580de0ca2c694c2007deac697fcaec1, but now is used just once.
> Flatten ast_struct_inner into ast_struct
