dtolnay/syn

src/expr.rs
tests/test_expr.rs

Hi David,
This is almost identical to the infinite loop parser. I wrote tests but I left them disabled until a little more of the language can be parsed. (I couldn't come up with a test that makes sense with what is currently available.)
If I get time to do some more of these, would you prefer them in a larger pull request? Maybe two or three at a time? Or do you prefer to keep your PRs small?
Let me know your comments and corrections! Thanks for taking the time for review!
--Greg

Added while loop parser and (currently ignored) tests.

---

src/expr.rs

This PR adds parsers for continue, break and return expressions. Please let me know any comments or changes and I'll be glad to implement them!

Add parsers for break, continue and return expressions.

---

.travis.yml
src/nom.rs

Work around Rust 1.12.0 bug

---

src/attr.rs
src/constant.rs
src/data.rs
src/derive.rs
src/expr.rs

Didn't get everything, but I added some. Also added some newlines between fields/variants for readability.

Add some doc comments.

---

src/generics.rs

Small convenience method for creating a `TyParam`.

Added From<Ident> for TyParam

---

tests/test_round_trip.rs

Found these while working on the attribute PR.

Small fixes for test_round_trip

---

src/data.rs
tests/test_macro_input.rs
tests/test_round_trip.rs

Update `visibility` rule for stabilized `pub(restricted)` syntax.

---

src/ident.rs
synom/src/span.rs

Now that under the hood they implement Debug

Derive Debug for Ident/Span

---

synom/src/cursor.rs

See https://github.com/alexcrichton/proc-macro2/issues/24. We do need to place an `Entry` in global storage, for `Cursor::empty`, but we can do this by adding an unsafe wrapper type which has the impl on it which we need.

Ensure that `Entry` is neither `Send` nor `Sync`

---

.travis.yml
src/fold.rs
src/visit.rs

I did the minimum amount of work to get them working again. It would probably be worth going over them again to make sure we aren't missing important fields.
Fixes #166.
NOTE: This is built on top of #168, so there are a ton of patches which aren't relevant here until that is merged.

Fix Visit and Fold to work on master

---

src/derive.rs
synom/src/lib.rs

Require exhaustive pattern matching in switch! parser

---

src/item.rs
src/macros.rs

Expose Synom impls for each kind of Item

---

src/macros.rs

Fix warning on unused to_tokens_call

---

src/gen/fold.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/item.rs
src/lib.rs

Extern types

---

src/gen/fold.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/item.rs
synom/src/tokens.rs

Support parsing the auto trait syntax

---

Cargo.toml
tests/common/mod.rs
tests/common/parse.rs
tests/common/respan.rs
tests/test_generics.rs
tests/test_grouping.rs
tests/test_precedence.rs
tests/test_round_trip.rs

Test with libsyntax instead of syntex

---

.gitignore
tests/common/mod.rs
tests/rust/clone.sh

Fixes #255. The travis cache ended up in a bad state.

Script to clone the rust-lang/rust repo

---

Cargo.toml
tests/common/mod.rs
tests/common/parse.rs
tests/test_precedence.rs
tests/test_round_trip.rs

Fixes #254. I have 54 cores so this runs instantly now. 😈 Any concerns?

Run round-trip and precedence tests in parallel

---

src/gen/fold.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/generics.rs
src/lib.rs
tests/test_derive_input.rs
tests/test_generics.rs

Groundwork for const generics

---

src/punctuated.rs

Square bracket indexing for Punctuated

---

src/lib.rs
src/synom.rs

As discussed in #314. Closes #314, fixes #313.

Provide a trait to invoke parser functions

---

src/lib.rs
src/parse_quote.rs
src/synom.rs

Some special cases for parse_quote

---

src/generics.rs
src/path.rs

Print generic params and generic arguments in the right order

---

src/expr.rs
tests/common/mod.rs

Support attributes on FieldValue

---

src/synom.rs

Just grabbing one commit from Federico's work in #367.

Document Synom::description()

---

src/token.rs

This fixes a regression introduced by the latest nightlies making an
`Underscore` parseable again.

Parse an Underscore as either an Op or Term

---

src/expr.rs
tests/test_should_parse.rs

Parse match arm containing block expression

---

src/punctuated.rs

Implement ExactSizeIterator for Punctuated iterators

---

src/token.rs

Closes https://github.com/dtolnay/syn/issues/419

Add $ token

---

src/expr.rs
src/item.rs
src/token.rs
tests/common/mod.rs

This PR is a modification of #450 for avoiding breaking changes (https://github.com/dtolnay/syn/issues/395#issuecomment-409012200).
cc: @dtolnay, @steveklabnik

accept async functions and closures as verbatim

---

src/spanned.rs

This checks the debug output of spans generated in Spanned::span
(quite a hack, yes..), and if it ends with "bytes(0..0)",
it assumes that it is invalid.
This fixes #508.

Check for invalid spans, and if so, use Span::call_site() instead

---

src/expr.rs
tests/test_pat.rs

Let me know if this is incorrect. I'm happy to make adjustments.
Fixes #517.

Parse arbitrary self types as PatIdent

---

src/token.rs

rename self/Self to SelfValue/SelfType

---

src/parse.rs

Support Debug and Display for ParseBuffer

---

src/expr.rs
tests/clone.sh

Parse leading vert in let-expressions

---

src/lit.rs

Add LitStr::parse_with

---

Cargo.toml

Ship build.rs to crates.io

---

Cargo.toml
build.rs
tests/test_generics.rs
tests/test_grouping.rs
tests/test_precedence.rs
tests/test_round_trip.rs
tests/zzz_stable.rs

Disable nightly-only tests on non nightly compiler

---

src/expr.rs

Parse implementation for ExprMatch

---

src/item.rs

Closes #618 by exposing `impl Parse for UseTree`.
Diff is best viewed [without whitespace](https://github.com/dtolnay/syn/pull/619/files?w=1).

impl Parse for UseTree

---

src/punctuated.rs

Implement Clone for the punctuated iterator types

---

src/ext.rs

```rust
trait IdentExt {
fn unraw(&self) -> Ident;
}
```
Strips the raw marker `r#`, if any, from the beginning of an ident.
- unraw(`x`) = `x`
- unraw(`move`) = `move`
- unraw(`r#move`) = `move`
In the case of interop with other languages like Python that have a different set of keywords than Rust, we might come across macro input that involves raw identifiers to refer to ordinary variables in the other language with a name that happens to be a Rust keyword.
The function below appends an identifier from the caller's input onto a fixed prefix. Without using `unraw()`, this would tend to produce invalid identifiers like `__pyo3_get_r#move`.
```rust
use proc_macro2::Span;
use syn::Ident;
use syn::ext::IdentExt;
fn ident_for_getter(variable: &Ident) -> Ident {
let getter = …
```

Extension method to unraw an ident

---

src/mac.rs
src/parse.rs

Methods to parse macro body

---

src/expr.rs
src/gen/fold.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/lib.rs
src/token.rs
syn.json
tests/debug/gen.rs
tests/test_expr.rs

Add expr variant for dot-await syntax

---

.travis.yml
src/buffer.rs
src/export.rs
src/gen/fold.rs
src/lib.rs
src/parse.rs

Add WASI target support

---

src/attr.rs

Add clarifying doc comment parsing example

---

src/ty.rs

Fixes bug where a single type surrounded by parentheses could be parsed as TypeTuple. It now requires a trailing comma when there is only one type.

Parse TypeTuple with one element now requires trailing comma

---

src/expr.rs

Implement quote::IdentFragment for Member and Index

---

src/buffer.rs
src/parse.rs

This avoids a few clones and allocations when performing lookahead peeks with `TokenBuffer::peek2` and `TokenBuffer::peek3`, including the `Rc::new` call in `TokenBuffer::fork`, and `TokenTree::clone` calls within `Cursor`.

Avoid unnecessary clones and allocations when peeking

---

src/parse_quote.rs

Allow parse_quote to parse Vec<Stmt>

---

src/lit.rs
tests/test_attribute.rs
tests/test_lit.rs

Support negative numeric literals

---

src/punctuated.rs

Add Punctuated::first_mut

---

src/mac.rs

This at least works when proc-macro2 is in fallback mode.
```console
error[cxxbridge]: expected `>`
┌─ tests/ui/include.rs:6:22
│
6 │     include!(<path/to);
│                      ^ expected `>`
```
There's no effect when proc-macro2 is in wrapper mode. For that to work we would need to preserve the real original Group token rather than just its Span in syn::MacroDelimiter. Only the proc_macro::Group can return a meaningful close span.
```console
error: expected `>`
--> $DIR/include.rs:6:13
|
6 |     include!(<path/to);
|             ^^^^^^^^^^
```

Somewhat better scope span for Macro::parse_body

---

codegen/src/fold.rs
codegen/src/visit.rs
codegen/src/visit_mut.rs
src/attr.rs
src/buffer.rs
src/data.rs
src/derive.rs
src/expr.rs
src/ext.rs
src/file.rs
src/gen/fold.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/generics.rs
src/item.rs
src/lib.rs
src/lifetime.rs
src/mac.rs
src/op.rs
src/parse.rs
src/parse_quote.rs
src/pat.rs
src/path.rs
src/punctuated.rs
src/spanned.rs
src/stmt.rs
src/ty.rs

Update doc comments about feature availability.

---

src/error.rs

Implement Extend<Error> for Error

---

src/expr.rs
src/item.rs
src/pat.rs
src/stmt.rs
tests/repo/mod.rs

Parse Or patterns

---

src/expr.rs
src/item.rs
src/pat.rs
src/stmt.rs
tests/test_pat.rs

See https://github.com/rust-lang/rust/blob/8858a435f3eef655df3e4fb6bec15d33e44a374e/src/test/ui/or-patterns/remove-leading-vert.stderr.
@taiki-e

Disallow leading vert in most places

---

src/ty.rs
tests/test_ty.rs

Fix some mut self cases that should not be accepted

---

src/stmt.rs
tests/repo/mod.rs

Closes #820. I don't know the exact rules but this passes the precedence test.

Fix precedence of attributes on binary expression

---

src/item.rs
tests/repo/mod.rs

Parse trait bounds on type alias item

---

tests/test_precedence.rs

Our precedence test wraps every layer of Expr in parentheses. But when it comes to const generics, turning `method::<0>` into `method::<(0)>` makes it invalid syntax because const generic arguments that are not a literal are required to be written inside curly braces.

Skip wrapping const generic arg in precedence test

---

src/item.rs
tests/repo/mod.rs

Parse const generic parameters on impl block

---

src/generics.rs
tests/repo/mod.rs

Parse ?const trait bounds

---

Cargo.toml

Don't make playground try to build `--features test`

---

src/expr.rs
src/ty.rs
tests/test_path.rs

https://github.com/rust-lang/rust/issues/72608

Parse macro metavariable in leading component of path

---

src/attr.rs
src/expr.rs
tests/test_expr.rs

Parse trailer exprs where the lhs is a Group

---

src/data.rs
tests/test_visibility.rs

https://github.com/rust-lang/rust/issues/72622#issuecomment-635779472

Parse empty None-delimited group as inherited visibility

---

src/expr.rs

Allows for parsing custom macro content in various places.
Fixes #515, #789
Note: naming as suggested per [this comment](https://github.com/dtolnay/syn/issues/515#issuecomment-430486650).

Make expr_no_struct public as Expr::parse_without_eager_brace

---

src/attr.rs
src/expr.rs
tests/test_item.rs

Move none-delimited attr behavior only to exprs

---

tests/test_expr.rs

Add test for tuple.0.0

---

src/expr.rs
tests/test_expr.rs

Parse tuple.0.0 as tuple indexing

---

src/file.rs

took me some time to understand why i can't run this example locally :)

Add `extra-traits` feature docs in file.rs

---

src/generics.rs
tests/repo/mod.rs

Parse const and type generic parameters in any order

---

src/lit.rs
tests/test_lit.rs

Allow 'e' as first character of float suffix

---

src/path.rs
tests/test_path.rs

Avoid panic on printing incomplete qualified path

---

src/lit.rs

Ran into another panic while fuzzing:
```rust
fn a() {
X.-0.9E999999
}
```
panics with `thread 'main' panicked at 'assertion failed: f.is_finite()', /home/purisame/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.19/src/lib.rs:1073:9`
but:
```rust
fn a() {
-0.9E999999
}
```
does not. Syn is calling a function that panics for non-finite floats when parsing expressions, so I've filtered those out.
This also raises some other questions -- why does parsing a non-finite float work in the first place?
```
expr: Lit(
ExprLit {
attrs: [],
lit: Float(
LitFloat {
token: 0.9E999999,
},
),
},
),
```
If we ever have f128, f80, etc. in Rust I think this behavior is fine. In which case, should the `other_suffix` case should fall back to
```
let stream = …
```

filter for float finiteness in proc_macro2 literal construction

---

src/lit.rs
tests/test_lit.rs

Depends on https://github.com/alexcrichton/proc-macro2/pull/252.
#897

Parse integer suffix beginning with `E`

---

src/lit.rs
tests/test_lit.rs

Depends on https://github.com/alexcrichton/proc-macro2/pull/255.

Parse float suffix beginning with `E`

---

src/item.rs

Implement Parse for Signature

---

src/pat.rs
tests/test_pat.rs

Fix parsing path Pat inside of None-delimited group

---

src/attr.rs
tests/test_meta.rs

Fix parsing an absolute nested meta path

---

src/parse.rs
tests/test_stmt.rs

Handle interaction of peek2 and peek3 with None-delimited groups

---

codegen/src/clone.rs
codegen/src/debug.rs
codegen/src/eq.rs
codegen/src/hash.rs
src/attr.rs
src/data.rs
src/derive.rs
src/expr.rs
src/file.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/hash.rs
src/generics.rs
src/ident.rs
src/item.rs
src/lifetime.rs
src/lit.rs
src/mac.rs
src/macros.rs
src/op.rs
src/parse.rs
src/pat.rs
src/path.rs
src/punctuated.rs
src/reserved.rs
src/stmt.rs
src/token.rs
src/ty.rs

doc(cfg(...)) on conditional trait impls

---

src/generics.rs
tests/repo/mod.rs

Allow lifetime params to parse after const params

---

src/item.rs
tests/repo/mod.rs

Parse unsafe extern blocks

---

src/item.rs
tests/repo/mod.rs

Parse unsafe mod

---

src/expr.rs
src/pat.rs
tests/repo/mod.rs

Parse const blocks in range patterns

---

src/expr.rs
tests/repo/mod.rs

Parse destructuring assignment

---

.github/workflows/ci.yml

Add a rustdoc job to CI

---

codegen/src/parse.rs

Any enum with a `doc(hidden)` variant is considered nonexhaustive, regardless of what the variant is named.
https://github.com/dtolnay/syn/blob/72c006c121036385d11bb1962c550e11404af71d/src/expr.rs#L227-L228
<br>
This facilitates implementation of #694.

Do nonexhaustive detection based on doc(hidden) attribute

---

src/expr.rs
src/item.rs
src/pat.rs
src/ty.rs

Provide an exhaustive matching idiom for syntax tree enums

---

src/custom_keyword.rs
src/custom_punctuation.rs

Suppress expl_impl_clone_on_copy pedantic lint in custom tokens

---

src/item.rs
tests/repo/mod.rs

Parse visibility on macro_rules

---

src/generics.rs
tests/repo/mod.rs

Parse placeholder type in type parameter position

---

src/item.rs
tests/repo/mod.rs

Parse static with omitted type

---

src/generics.rs
src/path.rs
tests/repo/mod.rs

Limit const generic default value expr to lit or braced expr

---

src/expr.rs

Parse outer attrs on ExprBlock

---

src/lit.rs

src/lit.rs:
line 43: infinte -> infinite

Fixed a tiny typo

---

src/expr.rs
tests/test_expr.rs

Swap closure body vs ExprRange rhs precedence

---

src/generics.rs

https://github.com/dtolnay/syn/blob/e6f9080447f3663890abcb469f52a35a9beb6a58/src/generics.rs#L174-L176

Use Option::get_or_insert_with in Generics::make_where_clause

---

src/path.rs
tests/repo/mod.rs

Parse ident as const generic default value

---

src/generics.rs
tests/repo/mod.rs

Replace unstable ?const syntax with ~const

---

src/data.rs
tests/repo/mod.rs

Parse anonymous braced struct field

---

src/stmt.rs
tests/repo/mod.rs

Parse trailing dot or question on braced macro invocation

---

src/ty.rs
tests/test_item.rs

Support trailing plus on impl trait type

---

src/ty.rs
tests/test_ty.rs

Fix TypeTraitObject parser to handle trailing plus at end of input

---

src/generics.rs
tests/repo/mod.rs

Parse ~const in where-clause

---

src/item.rs
tests/regression/issue1108.rs

Fix parsing trait impl with qself in trait type

---

src/parse_quote.rs

Add parse_quote_spanned macro = parse_quote + quote_spanned

---

src/expr.rs
tests/repo/mod.rs

Add support for let chains

---

src/expr.rs

Parse `for<…>` lifetime introducer on closures

---

src/buffer.rs

The names and abbreviations throughout this file are left over from before the finalization of the libproc_macro API (`sym` instead of `ident`, `op` instead of `punct`).

Improve variable naming in buffer.rs

---

src/ty.rs
tests/repo/mod.rs

`feature(dyn_star)`, tracked under https://github.com/rust-lang/rust/issues/91611.

Parse dyn* syntax

---

tests/test_expr.rs

Fix invalid use of insta snapshot inside a loop

---

src/attr.rs
src/data.rs
src/derive.rs
src/expr.rs
src/group.rs
src/item.rs
src/parse.rs
src/path.rs

Use peek-style punctuation argument for parse_terminated

---

src/ident.rs

Closes https://github.com/dtolnay/syn/issues/869

Add async, await, try to list of reserved keywords for ident and update docs link

---

src/ty.rs

Fix dyn Type parsing following PR 1098

---

codegen/src/visit.rs
codegen/src/visit_mut.rs

Fixes https://github.com/dtolnay/syn/pull/1261#issuecomment-1345787029.

Resolve borrow_deref_ref lint in generated code

---

src/attr.rs
src/error.rs
src/lib.rs
src/parse_macro_input.rs

I am working on a replacement for this.

Delete AttributeArgs type

---

src/ident.rs

https://github.com/rust-lang/rust/issues/105735

Work around rustdoc regression on Ident

---

src/stmt.rs

Follow-up to #1231.
Includes fix for https://github.com/dtolnay/syn/pull/1231#discussion_r1051508728.

Touch up PR 1231

---

src/pat.rs
tests/repo/mod.rs

Fix parsing of half-open range pattern with guard

---

src/expr.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
syn.json
tests/debug/gen.rs

Tracking issue: https://github.com/rust-lang/rust/issues/97362

Store bound lifetimes for Expr::Closure

---

src/expr.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
syn.json
tests/debug/gen.rs

Implement const_closures syntax

---

src/expr.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/pat.rs
syn.json
tests/debug/gen.rs
tests/test_size.rs

Allow qualified path on struct construction expr and pattern

---

tests/test_precedence.rs

This test was turning `if let Some(b) = b && b {}` into `if (let Some(b) = (b) && (b)) {}` which is not valid Rust syntax.

Do not parenthesize let_chains exprs in precedence test

---

src/expr.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/lib.rs
src/pat.rs
syn.json
tests/debug/gen.rs
tests/test_precedence.rs

This syntax does not appear to be on track for stabilization these days.

Delete box syntax data structures

---

src/expr.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/lib.rs
syn.json
tests/debug/gen.rs
tests/repo/mod.rs

Tracking issue: https://github.com/rust-lang/rust/issues/101728

Delete type ascription syntax

---

src/expr.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/pat.rs
syn.json
tests/debug/gen.rs
tests/test_expr.rs

Follow standard library naming for Range fields

---

src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/item.rs
src/lib.rs
syn.json
tests/debug/gen.rs
tests/test_receiver.rs

Replace Method terminology with associated function

---

src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/item.rs
src/lib.rs
src/stmt.rs
syn.json
tests/debug/gen.rs
tests/test_stmt.rs

Add Stmt::Macro variant

---

src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/lib.rs
src/path.rs
syn.json
tests/debug/gen.rs

As in `I: StreamingIterator<Item<'a> = T>`.

Parse generic associated type bindings in generic arguments

---

src/lit.rs

https://github.com/rust-lang/rfcs/pull/3348
https://github.com/rust-lang/rust/issues/105723

Preserve c"..." and cr"..." literal tokens

---

src/data.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/item.rs
src/lib.rs
src/restriction.rs
syn.json
tests/debug/gen.rs

https://rust-lang.github.io/rfcs/3323-restrictions.html

Implement restrictions

---

src/token.rs
syn.json
tests/debug/gen.rs

https://doc.rust-lang.org/nightly/reference/tokens.html#punctuation

Rename punctuation tokens to match naming used in Reference

---

src/token.rs

Copied from https://doc.rust-lang.org/1.67.0/reference/tokens.html#punctuation.

Document usages of every punctuation token

---

src/meta.rs

The previous message was too abrupt:
```console
error: expected ident
--> tests/ui/unexpected-literal/variant.rs:5:21
|
5 |     #[serde(borrow, "wat")]
|                     ^^^^^
```
vs:
```console
error: unexpected literal in nested attribute, expected ident
--> tests/ui/unexpected-literal/variant.rs:5:21
|
5 |     #[serde(borrow, "wat")]
|                     ^^^^^
```

Improve error message on unexpected literal in nested meta

---

Cargo.toml
fuzz/Cargo.toml
src/buffer.rs
src/discouraged.rs
src/group.rs
src/mac.rs
src/span.rs
src/token.rs
tests/test_size.rs

See https://github.com/dtolnay/proc-macro2/pull/366.

Change Span to DelimSpan in token::Paren/Brace/Bracket

---

src/attr.rs

This is an 18% improvement on the *benches/file.rs* benchmark.
Doc comments in the form `#[doc = r"..."]` are the most common attribute structure by far.

Optimize attribute parsing for the overwhelmingly common case

---

src/item.rs
src/stmt.rs

Fixes https://github.com/dtolnay/cargo-expand/issues/177.

Treat try keyword as 2015 ident in definition of try macro

---

src/error.rs
tests/test_compile_error.rs

Qualify `compile_error!`

---

src/punctuated.rs

Fixes: #1043
I'm not sure if/where you want tests for new functions...

add Punctuated::pop_punct()

---

src/expr.rs

Parse `builtin #` syntax

---

Cargo.toml
tests/repo/mod.rs

RFC: https://github.com/rust-lang/rfcs/pull/3348
Tracking issue: https://github.com/rust-lang/rust/issues/105723
Proc-macro2 implementation: https://github.com/dtolnay/proc-macro2/pull/395

Support parsing c-str literals

---

src/path.rs

Fixes https://github.com/serde-rs/serde/issues/2449.

Support single identifier as unbraced const generic argument

---

src/lit.rs

https://github.com/serde-rs/serde/issues/2242

Reject parse on LitStr containing suffix

---

src/path.rs
src/spanned.rs

Implement Spanned for QSelf

---

src/data.rs
tests/repo/mod.rs

Parse unnamed struct/union syntax

---

src/item.rs
tests/repo/mod.rs

Parse generic const items

---

src/item.rs
tests/test_precedence.rs

I am not sure that I want to commit to the parsing from #1499 until https://github.com/rust-lang/rust/issues/113521 is further along &mdash; e.g. has an accepted RFC.

Parse const item with generics as Verbatim

---

src/lit.rs

https://github.com/dtolnay/proc-macro2/issues/405

Parse rustc's representation of macro expansion error

---

tests/test_precedence.rs

This test will take an expression such as `(**self).get()`, replace the parens with invisible delimiters (`Delimiter::None`) i.e. equivalent to `$e.get()` where the `$e` metavariable contains `**self`, then print the syntax tree containing invisible delimiters into a TokenStream, reparse the TokenStream back to syn::Expr, and verify successful round trip.
Closes #840.

Add test for parsing Delimiter::None in expressions

---

tests/test_expr.rs
tests/test_pat.rs
tests/test_ty.rs

With one FIXME corresponding to https://github.com/dtolnay/syn/issues/1553.

Add tuple comma tests

---

src/pat.rs
tests/test_pat.rs

Fixes https://github.com/dtolnay/syn/issues/1553.

Fix ToTokens for PatTuple to insert trailing comma

---

src/op.rs

This should have been part of https://github.com/dtolnay/syn/pull/1367.

Parse binary assignment operators in non-"full" mode

---

codegen/Cargo.toml
codegen/src/parse.rs

Same reason as https://github.com/dtolnay/syn/pull/1614.

Remove codegen's dependency on thiserror

---

Cargo.toml
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/lib.rs
src/lit.rs
syn.json
tests/debug/gen.rs
tests/repo/mod.rs
tests/test_lit.rs

Add Lit::CStr to represent `c"…"` and `cr"…"` literals

---

src/expr.rs

This allows adding non-#\[cfg(feature = "parsing")\] associated items (in an upcoming PR) without having 2 separate `impl Expr` blocks rendered by rustdoc.

Consolidate into a single `impl Expr` block

---

src/expr.rs

If `input.parse::<BinOp>()` is Ok, then `input.peek(Token![=]) && !input.peek(Token![==])` is known to be false, `input.peek(Token![..])` is known to be false, and `input.peek(Token![as])` is known to be false, regardless of the precedences involved.
If `input.parse::<BinOp>()` is Err, then `!input.peek(Token![==])` is known to be true.

Adjust loop structure of parse_expr

---

src/expr.rs

Remove recursion from parsing of Expr::If

---

src/expr.rs

Remove recursion from printing of Expr::If

---

src/classify.rs
src/mac.rs
src/stmt.rs

Wrap let-else expression in paren if needed

---

src/expr.rs
tests/repo/mod.rs

Fix parsing of struct literal in match guard expression

---

src/lib.rs

https://github.com/rust-lang/rustfmt/issues/6176

Do not format gen module because of rustfmt bug

---

src/buffer.rs

Previously, jumping forward from a `Entry::Group` to the matching `Entry::End` was cheap, but jumping backward from `Entry::End` to the matching `Entry::Group` required a linear scan of all the tokens in between.

Optimize reverse iteration of TokenBuffer

---

src/expr.rs
src/precedence.rs

Equivalent of https://github.com/rust-lang/rust/pull/126893.

Eliminate Postfix precedence level

---

tests/repo/mod.rs
tests/test_unparenthesize.rs

This test revealed the edge cases in #1698, #1699, #1700.

Test parenthesis insertion against rustc repo

---

src/ty.rs
tests/repo/mod.rs

Parse unnamed variadic args inside function pointer types

---

src/expr.rs
tests/repo/mod.rs
tests/test_precedence.rs

Parse explicit tail calls

---

src/expr.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
syn.json

Support parsing Expr::Tuple in derive

---

src/file.rs
src/lib.rs

Use more concise `read_to_string` to read file content.

Minor doc improvement

---

src/expr.rs
tests/test_expr.rs

Fix infinite loop on chained comparison

---

src/item.rs

Fix construction of UseGroup containing crate roots

---

src/ty.rs

Reject trait bound containing only precise capture

---

codegen/src/clone.rs
codegen/src/debug.rs
codegen/src/eq.rs
codegen/src/full.rs
codegen/src/hash.rs

In preparation for TypeParamBound changes for https://github.com/dtolnay/syn/issues/1677.

Generalize codegen support for mixed "derive"/"full" enums

---

src/classify.rs
src/gen/clone.rs
src/gen/debug.rs
src/gen/eq.rs
src/gen/fold.rs
src/gen/hash.rs
src/gen/visit.rs
src/gen/visit_mut.rs
src/generics.rs
src/lib.rs
src/ty.rs
syn.json
tests/debug/gen.rs
tests/test_ty.rs

Closes https://github.com/dtolnay/syn/issues/1677.

Add TypeParamBound::PreciseCapture

---

src/expr.rs
src/parse_quote.rs

Allow Vec<Arm> in parse_quote

---

tests/test_expr.rs

This makes a difference for testing larger expression depths.

Speed up test_permutations by bypassing parsing

---

src/expr.rs
src/fixup.rs

This is going to be needed for correctly parenthesizing bailouts.

Track previous and next operator's precedence in fixup context

---

src/generics.rs
tests/repo/mod.rs

Closes https://github.com/dtolnay/syn/issues/1888.

Parse const trait bound with bound lifetimes

---

src/generics.rs
tests/repo/mod.rs

Closes https://github.com/dtolnay/syn/issues/1900.

Parse bound lifetimes with lifetime bounds

---

tests/repo/mod.rs

Closes https://github.com/dtolnay/syn/issues/1901, which is a duplicate.

Fix duplicated async trait bound issue
